### ISSUE TITLE
Conditional has a dodgy Applicative instance

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1443]
`Conditional` has a dodgy `Applicative` instance: `(<*>)` should be associative, but it is not technically because predicates are combined using `makeAndPredicate` (not associative). This is not unsound because `makeAndPredicate` is _morally_ associative, but it would still be good to fix this up. Probably, we should make the `predicate` field of `Conditional` into a `MultiAnd (Predicate _)`; that would be properly associative and it might help with some other things (e.g. #1391).

**Comment by ttuegel** [comment]
Another option would be to make `makeAndPredicate` associative, but that requires either changing the representation of `Predicate` or accepting quadratic performance. The latter is not acceptable, and we may not want to commit to the former yet.

**Comment by virgil-serbanuta** [comment]
In favor of the former: I think we already have an `n^2 log n` algorithm (`n` for the depth of the `and` part of the expression, and `n log n` for the processing that takes place at each level): https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Simplification/And.hs#L223

**Comment by ttuegel** [comment]
Using something like `MultiAnd`, but backed by a `Set` (for example), `(<>)` has complexity `O(n log n)`.

**Comment by ana-pantilie** [comment]
If we decide to change the representation of Conditional, we'd need to do https://github.com/runtimeverification/haskell-backend/issues/1530 first.

**Comment by ana-pantilie** [comment]
@goodlyrottenapple suggests the following investigation: remove https://github.com/runtimeverification/haskell-backend/blob/9ea642db346c529b75cc1f7963360064c5092860/kore/src/Kore/Internal/Conditional.hs#L139 and see how many changes we'd need to do.

If the code can be refactored easily to use other functions instead of the applicative instance then we can go forward with this. If it turns out it creates some other nested issues then we need to reassess the problem.
