### ISSUE TITLE
Feature wishlist for REPL

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/haskell-backend#1625]
The list of useful features for REPL I can think of, in the order of their priority:
- option to print pretty-printed config and other data. This would save a lot of time on repetitive tasks and would get the highest ROI in terms of invested time.
- Improve help inside REPL. I don't understand how to use the last paragraph, starting with "Rule names can be added in two ways"
- Print the rule that was applied to reach present node.
- Some capability to debug function evaluations. In Java Backend we print all applied function rules.
- Print config diff between present node and its parent. Pretty-printed.
- Option to pretty-print just some cell or a constraint from the config. I guess this can be done through some regex over kore. Most useful for k.
- Option to print k cell for a range of steps. Like [print k 90-100].
- stepf [n]: it must advance to first branching point which has more than one leaves after n steps were executed.
For example, for stepf 10, and this graph:
```
      0
      5
     / \
    6    7
    |   /  \
bottom  8...  9...
```
it must advance to node 7.

**Comment by ttuegel** [comment]
> option to print pretty-printed config and other data

There is an output filter for doing this. I must admit, I don't know how to use it because I'm always debugging Kore, but I think @yzhang90 does.


> Print the rule that was applied to reach present node.

This is done by the `rule` command.

> Some capability to debug function evaluations. In Java Backend we print all applied function rules.

You can pass the option `--debug-applied-rule IDENTIFIER` to see all the applied function rules for `IDENTIFIER`. Limitations:
 
- you need the Kore symbol name, not the K label.
- you can't change this option on-the-fly in kore-repl (I think).

> Option to pretty-print just some cell or a constraint from the config. I guess this can be done through some regex over kore. Most useful for k.

I think we can convince the frontend to generate a Kore pattern (corresponding to a K term) for us to match. This is how `krun --search` works.

**Comment by virgil-serbanuta** [comment]
FWIW, here's one of my recent chats with @yzhang90 , this works properly only with kore-exec, not all the flags work with the repl. @ttuegel I thought `--debug-applied-rule` does not work in the repl, but I may be wrong.

-----

yi.zhang  9:45 PM
I was asked how to debug a concrete run, I'm not sure what log entries are useful for that...

virgil.serbanuta  9:53 PM
ah, I see.
I never tried it, but I would be tempted to use --depth to locate the step where the issue occurs, then --log-entries DebugAppliedRewriteRules --log-level info to see if the issue is related to which rewrite rules are being applied. If the issue is related to function simplification, then --log-entries DebugAxiomEvaluation --log-level info should dump all the axioms being used, while --debug-simplification-axiom symbol-identifier should focus on the given identifier (I don't remember if it also needs --log-entries DebugAxiomEvaluation, I guess it doesn't). For both --log-entries DebugAxiomEvaluation and --debug-simplification-axiom symbol-identifier you should be able to add --debug-simplification-axiom-patterns to see what is being evaluated and what is the result.

**Comment by ttuegel** [comment]
> I thought `--debug-applied-rule` does not work in the repl, but I may be wrong.

I don't think it works as an option to the `log` command, but it should work on the command-line.

**Comment by virgil-serbanuta** [comment]
```
$ /home/virgil/runtime-verification/kore/.build/kore/bin/kore-repl /home/virgil/runtime-verification/evm-semantics/./.kprove-2020-02-10-19-23-35-054-56f6ec80-a364-48b7-9d1c-e2770046b976/vdefinition.kore --module VERIFICATION --prove /home/virgil/runtime-verification/evm-semantics/./.kprove-2020-02-10-19-23-35-054-56f6ec80-a364-48b7-9d1c-e2770046b976/spec.kore --spec-module TOTALSUPPLY-SPEC --output /home/virgil/runtime-verification/evm-semantics/./.kprove-2020-02-10-19-23-35-054-56f6ec80-a364-48b7-9d1c-e2770046b976/result.kore --debug-appled-rule thing
Invalid option `--debug-appled-rule'

Usage: kore-repl [--version] [MAIN_DEFINITION_FILE] [--module MAIN_MODULE]
                 [--prove SPEC_FILE] [--spec-module SPEC_MODULE]
                 [--graph-search GRAPH_SEARCH] [--bmc] [--save-proofs ARG]
                 [--smt-timeout SMT_TIMEOUT] [--smt-prelude SMT_PRELUDE]
                 [-r|--run-mode] [--repl-script REPL_SCRIPT]
                 [--output PATTERN_OUTPUT_FILE]
  REPL debugger for proofs
```

**Comment by virgil-serbanuta** [comment]
ok, that has a typo, but it's the same with `--debug-applied-rule`

**Comment by denis-bogdanas** [comment]
@virgil-serbanuta It would be nice to see a demo on how would you go to use those options. Or a writeup on how you debugged an issue using some of them, in the PR for that issue.

**Comment by virgil-serbanuta** [comment]
@denis-bogdanas 
I could try, but:
1. I have a lot of work to do for RV-Match (well, actually I only have a tiny amount of work, but everything is new so I'm very slow). This will probably have to wait.
2. I would need something to debug. I don't think I have past examples ready.
3. A writeup would take a lot of time, a demo or a "pair debugging" session with you may be better, especially since I don't usually know/understand the semantics I'm debugging well enough and I could use help with that.

**Comment by yzhang90** [comment]
To complement what @ttuegel said about the first item:
`konfig` command is the alias of config and then passing the result to kast. In order to use it, you need to be in the same dir as the definitoin(e..g, .build/defn/symb-test)

**Comment by denis-bogdanas** [comment]
@virgil-serbanuta Then next time I'll get stuck with something that needs function evaluation maybe you can show how you would go on debugging it. Or @yzhang90 . I'll try your instructions above first.

**Comment by denis-bogdanas** [comment]
Is there a `kore-exec` option to continue execution of good branches even when other branches fail? Similar to `stepf` in RELP?

**Comment by ttuegel** [comment]
> Is there a `kore-exec` option to continue execution of good branches even when other branches fail? Similar to `stepf` in RELP?

I'm a little bit confused about this, because that isn't quite what `stepf` does. But, to answer your first question: no, because `kore-exec` originally worked like this—it would not exit until all execution branches had terminated. We found this was not useful because if one branch was "bad" then the branches that appeared "good" actually were not. Typically, the prover would get a "good" and a "bad" branch by splitting on some condition that it shouldn't even consider in the first place. If that's not what you are seeing, and you think it would be useful, I'm open to adding the original behavior back as a flag.

**Comment by denis-bogdanas** [comment]
@virgil-serbanuta How to find symbol identifier of a given rule? I it the rule label?

**Comment by virgil-serbanuta** [comment]
If you want to find a symbol's name:

1. You can search the .kore file to find the (long) kore name.
2. You should be able to use the klabel directly, if any, but I'm not 100% sure it works (it should, though).
