### ISSUE TITLE
Global state or Explored states in K?

### ISSUE THREAD

**Issue by LaifsV1** [runtimeverification/haskell-backend#1840]
As in the question: https://stackoverflow.com/q/61858563/3002076

I mainly use K for model checking and symbolic execution of different languages. This requires building the full computation tree of a given program, i.e. using the `--search` option to branch wherever possible. This leads a lot of redundancy in the paths, since many branches produce semantically identical configurations.

One solution to this is to have global state where I can add into some set all the configurations I've seen so far. Because I almost exclusively use the `--search` option, implementing a kind of state monad, whereby I pass the set of configurations seen so far, doesn't seem to work, since each path explored with the `--search` option is independent (as should be). It would be nice to have some kind of communication component that is globally shared between all the configurations being expanded in every path. This would allow the implementation of the explored set (and more, such as keeping track of all transitions explored in every path to directly output a transition system).

My question is if this is currently possible to do in K as it is (e.g. by somehow nesting configurations to explore inside a bigger configuration that is static, or some other syntax I'm not aware of). If not, would a global component that is shared between all configurations pending to be evaluated be a feature worth implementing? 

One could also think, at least, of a built-in implementation for explored states, but most likely, configurations are going to be syntactically different as computation progresses (e.g. different names, more names, symmetric terms, etc). Unless it's possible to tell it how to store and compare configurations for some defined notion of structural congruence, an implementation internal to K may be limited in use.

**Comment by ehildenb** [comment]
To be clear, I don't think that the K user should have access to this global cache of states @LaifsV1 to solve your issue, because that would require a meta-level. Instead the backend should just perform state folding to help with your scenario.

State folding is where the backend will check every new explored state to see if it's subsumed in some previously explored state. Then instead of continuing to explore that path, you put a back-edge in the exploration graph to the previous node along with the substitution that shows that the new node is subsumed in the old node. This can often times make infinite symbolic execution graphs finite (depending on how powerful your state-folding techniques are). The Maude model checker does this automatically when doing symbolic execution, for example.

**Comment by LaifsV1** [comment]
I see. It seems state folding is precisely what I am thinking about. Especially if K can report the back-edges. Would the state folding be something the user can access? e.g. allowing the user to define a normal form for states, or maybe the comparison function.

Incidentally, is K currently able to output the set of edges between configurations?

**Comment by ehildenb** [comment]
Yes, you can use the `kore-repl` to debug proofs with the Haskell backend (instead of `kore-exec`) by passing the argument `--haskell-backend-command kore-repl` to `kprove`.

In the `kore-repl` you can do `help` to see the available commands, of particular interest are `stepf` and `graph` for your purposes.

Currently because there is no state-folding, there will be no back-edges in the graph.

**Comment by LaifsV1** [comment]
So far, I've been using `kompile` and `krun --search`. So I wasn't aware of the other tools. I couldn't find the command's I'd like or the usage of `kore-repl`. Is there documentation somewhere on the usage of `kore-exec`, `kore-repl` and `kprove`? What does each tool do?

**Comment by ana-pantilie** [comment]
Will this be solved externally (by using pyk)? Do we want to do this in kore-exec?
