### ISSUE TITLE
Support --deterministic-functions

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2127]
The backend should support the `--deterministic-functions` option by:

1. grouping function definition equations by priority, and
2. throwing an error if two equations in the same priority level could every apply to the same term.

**Comment by ehildenb** [comment]
Questions posed on slack:

-   Should (2) be done with narrowing or rewriting?
    Rewriting allows users to write some definitions without modification but is unsound in general:

    ```
    for(X) => X *Int 3 requires X <=Int 0 [simplification]
    foo(X) => X *Int 2 requires X >=Int 0
    foo(X) => X *Int 3 requires X <Int 0
    ```

    on input `foo(X) /\ X <=Int 0` would thrown out by narrowing, but is actually OK and would be accepted by rewriting.

-   Should (2) do any checks of the resulting narrowed/rewritten terms for equality?
    The above example would likely be accepted by narrowing if we also check for term equality afterwards.

**Comment by ehildenb** [comment]
Another option is to implement a confluence checker in the Haskell backend.
There is a simple algorithm for confluence checking that is _sound_, _impcomplete_, but _effective_ (suffices for the vast majority of cases). A sketch:

1.    For every pair of equational rules in the same priority group `([rule1]: L => R requires C ensures D, [rule2]: L' => R' requires C' ensures D'`) and find critical pairs `L #And { L #Equals R } #And C #And D`.
2.    For each feasible critical pair `L #And { L #Equals R } #And C #And D`, apply `[rule1]` to it with _narrowing_ to get `T #And COND`, and `[rule2]` to it with _narrowing_ to get `T' #and COND'`.
3.    Check if `{ T #And COND #Equals T' #And COND' }` using rewriting. If unable to prove this for each critical pair, reject definition.

In the many cases, this algorithm is sufficient to show confluence of a definition. The benefits are that (i) it can run once at kompile time to check the definition statically, and (ii) it makes the behavior of choosing the first equational rule that applies with _rewriting_ at runtime sound.

To make this _more_ complete (impossible in general to have a complete confluence checker), you can replace `rewriting` in step (3) with `narrowing`, but this makes the algorithm not terminate. To make this faster (many tools use this technique, including Maude I think), you can replace `rewriting` in step (3) with `one step of rewriting followed by queries to SMT solver`.

**Comment by ttuegel** [comment]
I like the idea of having a separate tool for confluence checking. This might catch many potential errors before they actually bite in practice.

I have some questions about this step:

> Select every pair of equational rules (i) in the same sort, (ii) in the same priority group, and (iii) with disjoint variable names `([rule1]: L == R, [rule2]: L' == R'`) where `L #And L'` is not `#Bottom` (this is a critical pair, and we assume that any side-conditions given by `requires` and `ensures` are contained in `L`, `L'`, `R`, and `R'`).

1. "In the same priority group" would seem to mean that the rules have the same function symbol at the top, so why is it necessary to say "in the same sort"?
2. Evaluating `L #And L'` that we evaluate (with rewriting) the function at the top of the rules, which already assumes confluence. Do you mean to do syntactic unification here instead of `#And`? Or maybe something like semantic unification, but only on the arguments of the function symbol?

**Comment by ehildenb** [comment]
1.  I wasn't aware that "in the same priority group" meant that they have the same function symbol on top. But I think we need to check that it's enough to only consider critical pairs between equational rules with the same function symbol on top, or if we need to consider all equations within the same sort. For example, the patterns `X -Int 2 #And { X <=Int 5 ==Bool true }` and `Y +Int 1 #And { Y <=Int 2 ==Bool true }` intersect on the elements of sort `Int` that they can represent, but they don't syntactically unify. Would we need to consider critical pairs between these terms or not? I guess it depends on the shape of the formula `phi(RULE, PATTERN)` is, which applies a rule to a pattern to produce the next state.
2.  I guess I thought that `#And` meant semantic unification, but whatever the formula for semantic unification is what I think we need. But I don't know if it's enough to only consider terms with the same function symbol at the top (I honestly actually don't know). I think we need to make sure we have a clear definition of "confluence" before we can answer these questions. The above psuedo-algorithm is just my "porting" of how Maude's confluence checker works, but things can be different in Matching Logic from Equational Logic.

**Comment by ttuegel** [comment]
> I guess I thought that `#And` meant semantic unification, but whatever the formula for semantic unification is what I think we need.

`#And` _does_ mean semantic unification, that's what I'm saying the problem is. Given two function symbols `f` and `g`, how do I decide semantically that `f(X) #And g(Y)` is not `#Bottom`? Evaluating the functions _assumes_ confluence.

**Comment by sskeirik** [comment]
Confluence checking is tricky because equational rewriting typically _assumes_ confluence, as you pointed out, but one cannot depend on this behavior during confluence checking. A more simplistic notion of rewriting that does not make any assumptions about confluence is required for doing confluence checks. 

This algorithm becomes more complex if one is doing confluence checks for rewriting modulo axioms. In the fully general case, you have to attempt to unify equations that have different top symbols because they may become unifiable modulo axioms. I think there are some axioms that are builtin into the backend, if I recall correctly, and these would require special treatment.

I don't remember the details at the moment, but I do have papers on this in my stash of pdfs that I could distribute if there is interest later.

**Comment by ttuegel** [comment]
> In the fully general case, you have to attempt to unify equations that have different top symbols because they may become unifiable modulo axioms.

You made a point above about needing a more simplistic notion of rewriting to prove confluence. In this case, we have builtin equations and user-defined equations. If I understand correctly, to prove confluence we would be rewriting with user-defined equations (treating them as rewrite rules) modulo builtin equations; i.e., we would be doing unification modulo builtins. Is that right, or is that too simplistic?

**Comment by ttuegel** [comment]
I had a lengthy discussion today with @sskeirik about confluence checking for Kore. We don't think that this idea is ripe for implementation yet. There are several theoretical issues that must be resolved so that we can be sure we're doing the right thing. Here I will attempt to summarize the most important ones:

- When we talk about confluence, or convergence, we are asking if a set of rules is confluent _under a particular rewriting relation_. For Kore functions, the rewriting relation has not been formalized. We would need to formalize it before we can even begin. And, for our convergence proofs to be useful to users, we would also need all backends to agree on this formalization.
- Because terms and connectives exist on the same level in matching logic, we need to carefully consider how we want to define confluence and joinability.
- We would be considering confluence modulo certain axioms: associativity, commutativity, identity, nilpotency (for built-ins), sort injection and overloading, etc. The existing literature deals with axioms that are linear and regular, which causes problems for identity and nilpotency axioms.

We think that these problems can be solved, but it would not be appropriate to venture into implementation until we had treated them formally.

**Comment by ehildenb** [comment]
I think we can have a simpler tool which does well enough. Just given two function definitions in the semantics `L1 => R1 requires C1` that could apply at the same time (same head symbol, same priority), check if (i) `(L1 #And L2) #And (C1 #And C2)` is `#Bottom` and (ii) `R1` and `R2` are single-valued. This would instead check that the two equations _cannot_ apply at the same time, and that they are single-valued, which implies confluence. You can have confluence and _not_ have this condition, but I think this condition checks that the function is single-valued, which implles confluence.

I figured the same simplifier which is used to simplify side-conditions/path-conditions could be used in checking (i), and that checking (ii) shouldn't be hard to do using a syntactic check (perhaps a "constructor-like" check). May even be safe to use the equations to check this, but a simpler version could just do the unification `L1 #And L2` to get substitutions `alpha1 ... alphan`, and then ask Z3 to check that `(C1 #And C2)` instantiated with each substitution is `unsat`.

My gut tells me this should work in 90% of cases to show functions in K confluent, because in many semantics we already strive to make sure that the function rules are mutually exclusive in this way.

**Comment by ttuegel** [comment]
You are right: checking that a pattern is at most single-valued is a syntactic.

I actually made a similar comment about exclusivity to @sskeirik. It's a strong restriction, but it's probably a good habit to define functions that way. But, we cannot use the existing simplification routine to check this, because it _assumes_ exclusivity. We have all the pieces to build this routine, though.

**Comment by sskeirik** [comment]
I think that this simpler check is sufficient in many cases and will do what we want.

We still need a decidable and complete unification algorithm in order to be sure that all of the critical pairs are generated between any two function rules with the same top symbol. I'm assuming we have this in many cases --- and we can probably define a syntactic subset which has this property.
