### ISSUE TITLE
New workflow to replace kore-repl

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2489]
There are some unfortunate deficiencies around `kore-repl`, that we are not likely to be able to solve:

1. The user interface is pretty limited for an interactive program. It allows to define aliases, and it has very primitive scripting capability.
2. Unlike `kore-exec`, it can prove specifications but not run programs.
3. Unlike `kore-exec`, it can only work on proofs that fit entirely in memory.

After struggling with `kore-exec` and `kore-repl` myself, and watching others, this is my proposal to replace both with a new workflow based on a common set of primitive commands. This solves the problems above:

1. The user can interact with the primitive commands directly in their shell, which is a capable interactive scripting environment they already know. This essentially replaces the functionality of `kore-repl`, but has a lower barrier to entry for users to extend.
2. We can replace `kore-exec` with a script that will run the primitive commands in the right sequence to prove a specification or run a program, so there is no divergence between the automated and interactive workflow.

## Design

The backend will maintain a database of objects: programs, claims, rewrite rules, equations, ... almost anything the backend knows about. Each object will be identified by a unique hash according to its type, so `program/hhhhh...` will refer to a program configuration, `claim/hhhhh...` will refer to a claim, etc. The user will interact with the backend through a single `kore` command with many sub-commands. The primitive commands are described below. It's not hard to see that the existing `kore-exec` and `kore-repl` functionality can be reproduced with simple wrappers around these commands. These wrappers may be as simple as Bash scripts, but in some cases we may want to avoid the overhead of spawning many processes and write the wrappers in Haskell.

#### init

`kore init KORE --module MODULE --syntax SYNTAX`

Parse and validate the Kore definition in file `KORE`. Open the module named `MODULE`. Use the Kore definition in file `SYNTAX` for printing with `kprint`.

The `init` sub-command may be run more than once, in which case the backend will try to update its database with a new definition. This may fail if the new definition would invalidate any static objects in the database. So, the user cannot add symbols (this would invalidate programs and claims) but they could add or remove rewrite rules.

All other sub-commands require this command has been run in the current directory.

#### add-program

`kore add-program PGM`

Parse and validate the program in file `PGM`. Output the object identifier(s?) of the added program.

#### add-claims

`kore add-claims SPEC`

Parse and validate the specification (claims) in file `SPEC`. Output the object identifiers of the new claims.

#### add-pattern

`kore add-pattern PATTERN`

Parse and validate the pattern in file `PATTERN`. Output the object identifier of the new pattern. A pattern is used for matching in search mode. The only real difference between a pattern and a program is that we don't ever rewrite a pattern.

#### switch

`kore switch OBJECT-ID`

Focus on a particular object. All sub-commands that take a single `OBJECT` argument can have that argument omitted, and they will use the latest focused object instead.

#### status

`kore status [OBJECT-ID]`

Print the status of the program or claim identified by `OBJECT-ID`.

#### show

`kore show [OBJECT-ID]`

Print the object using `kprint`.

#### next

`kore next [OBJECT-ID]`

Advance the program or claim `OBJECT-ID` by one step. Output is the list of object identifiers of the immediate successors.

#### match

`kore match PATTERN-ID [PROGRAM-ID]`

Match the identified pattern against the program `PROGRAM-ID` (or the current focus). The `match` sub-command would be used to implement search.

## Risks

The biggest risk I foresee is up-front: we need a capability to quickly load and store state from a database. We already have a simple SQL interaction layer. We would probably extend this with the capabilities we need, because the data we are interested in is primarily relational. Building on an existing capability would help mitigate risk, but this will still be a significant up-front effort.

Except for the up-front effort required to extend our database capabilities, this proposed interface is largely just rearranging and repackaging existing functionality of the backend, so that after the up-front work I expect the rest of the migration to be low risk.

**Comment by virgil-serbanuta** [comment]
This looks really interesting.

I think that this would need a good way of doing garbage collection. With the current tools, whenever a process dies, its state simply disappears (which has its good and bad points) but it's not clear to me what would happen with the new approach.

**Comment by ttuegel** [comment]
> I think that this would need a good way of doing garbage collection. With the current tools, whenever a process dies, its state simply disappears (which has its good and bad points) but it's not clear to me what would happen with the new approach.

I didn't articulate this in the design, but I imagined that the backend would only add new program or claim states to the database at the end of each step. `add-{program,claims}`, `match`, and `next` are the only commands that should change the database, and I'm thinking of them as atomic operations. I think that disk space is cheap enough that garbage collection of the execution graph is not necessary. For the same reason, I also expect that if the program crashes in one of those steps then the database is not modified.

**Comment by virgil-serbanuta** [comment]
My two cents: Having a command-line interface for the repl would make it more flexible, since people not part of the Haskell backend could develop their own tools, and they can do it in their language of choice.

As an example, it would probably be easier to develop interactive tools (e.g. a GUI), or to filter the logs through `kast` or `kore-print`. Of course, both of these are also doable with a Haskell repl (one can just communicate with the process directly for the former, or save the logs to a file first, then process that file for the latter).

**Comment by ana-pantilie** [comment]
David asks how much memory the DB will need to store.

**Comment by andreiburdusa** [comment]
The only time I did some database interaction, when I was learning from [HPFP](https://lorepub.com/product/haskellbook), I also used SQLite. Since it's also what we currently use I feel like this is the default option. And since I don't have experience I don't see reasons why we should switch to something else :)

**Comment by emarzion** [comment]
On the issue of scripting, I agree that just in terms of flexibility it makes most sense to deliver the atomic commands as executables and let the users deal with scripting themselves.  And if there was any appetite for a korescript there would still be the option to implement that later without too much effort.

On the issue of databases, what features of the existing and/or anticipated code would depend on the specifics of SQLite versus SQL generically?

**Comment by ana-pantilie** [comment]
@emarzion We already have some code which seems tied to using SQLite, but I am not certain that it isn't flexible enough to allow using another database if needed. I have https://github.com/kframework/kore/issues/2866 open for determining exactly that, among other things that will be necessary.

**Comment by ana-pantilie** [comment]
I just found the package we currently use for the SQL interaction: https://hackage.haskell.org/package/sqlite-simple-0.4.18.0/docs/Database-SQLite-Simple.html

**Comment by ana-pantilie** [comment]
We need to think about and discuss more details regarding the `kore` commands and how they interact. In the following I'm assuming we will use SQLite since this is what our current SQL interaction layer uses.

### `kore start`
I believe we first need a command which creates a new DB, let's say `kore start <args...>`. This will be the DB used by all the other commands, it will act as the memory used for running "one session" of the backend. What this means is that each "instance" of the backend will have its own DB. This is where we can do some initializing of the DB, and output the DB name in some appropriate way for the subsequent `kore` commands to have access to it.

This will also need to begin a Z3 instance to which subsequent commands have access. I am a bit concerned about how we will handle Z3, since it needs periodic re-initialization and there's also the issue that it sometimes crashes. Can these issues be solved by adding separate commands which restart/re-init Z3? More discussion is necessary. 

### `kore init`
This command will work as stated in the description above. This will already give much more flexibility, compared to how the backend is now, as the semantics can be updated dynamically.

The command will populate the DB with all the information we currently keep in the `VerifiedModule` type. This needs some investigating, meaning reading the code which uses `VerifiedModule`.
I'm tempted to say we don't even need `VerifiedModule`, which is an intermediate representation of a syntactially validated kore module, which we can internalize further into the types we actually use for execution. I think that, ideally, we should just jump to keeping the internalized sorts, symbols, rewrite rules and equations, but things might be more complex so we have to be more careful to not leave anything out.
For example, I can't remember right now how these were used, but the `MetadataTools` might cause some issues? I'm not sure, just jotting this down in order to not forget to pay close attention to what happens with those.

This command should also initialize Z3, regardless of whether we have separate commands to do that.

To summarize, we need to carefully understand the code which uses `VerifiedModule` in order to figure out what needs to be stored in the DB for execution.

### `kore add-<program/claims/pattern>`, `kore switch`, `kore status`, `kore show`, `kore match`
These commands seem pretty straightforward to me, so I don't really have anything to add about them. 

### `kore next`
This one hides most of the complexity of this design overhaul.

First of all, depending on what type of object is focused on (or received as an argument), this will dispatch a different execution procedure.
For programs, it will be either the normal symbolic execution strategy or the search strategy. Again, we need to investigate, refresh our memories on the differences in implementation between the two, and figure out what needs to be done. They might actually have the same implementation, but I am not 100% sure.
For claims, it will always be the proof strategy, which depends on whether the claim is one-path or all-path. That information should be available.

Second of all, each program/claim will have its own associated execution graph, updated by this command. How will we represent these graphs in the DB efficiently? This needs some careful consideration.

I also have big concerns regarding performance here. I'm pretty sure that running multiple `kore next` commands will be much slower than running `kore-exec` as it is now, which becomes an issue if we want to replace `kore-exec` as well. We need to think about how we can still keep this performance when necessary.

### Conclusion
Putting it simply, these changes will move many of the information used by the backend into a global state (the DB) and I don't know how desirable that is. Maybe that's not really an issue, let me know what you think.

Anyway, my post is to help us get a better understanding of what the commands will do and need. Please let me know if there's something you don't agree with, or if there's something I've missed. We all need to discuss these commands in quite some detail.

If we decide to go forward with this description, we need to carefully design the DB, keeping all of the discussed details in mind.

**Comment by ana-pantilie** [comment]
I almost forgot: these commands sound like the bare-minimum to me. `kore-repl` has more functionality which we should try to port over to this new design. An example would be removing nodes from the execution graph. Of course, we will add all these features afterwards.

**Comment by dopamane** [comment]
Questions:
What happens if the user sends two commands simultaneously?
How to handle Z3? Reinit? Restart?
Investigate current kore-repl execution graph memory usage.
CLI libraries to handle sub-commands?

**Comment by dopamane** [comment]
I think we should break `kore start` and `kore init` into smaller/more primitive commands like `kore db create`, `kore db populate`, `kore smt start`, `kore smt reinit` etc. We should try to provide a clearly defined and bare-minimum set of primitive instructions and avoid exposing more complex instructions (doing multiple things) because that should be implemented at the script level. Once we have a better idea of common user scripting patterns then we can enhance the instruction set for performance or simply provide a library of commonly used scripts.

DB initialization, needs to create a name/session ID which will be paired with each DB transaction to ensure multiple Kore sessions can operate simultaneously without corrupting the database. This means that the DB name/session ID needs to be saved and retrieved for each subsequent instruction at the script level.

Similarly for Z3 initialization, it needs to output some sort of process ID. The user will have to save the ID and then retrieve it for each subsequent instruction at the script level. This might be a pain-point for the user.

[optparse-applicative](https://hackage.haskell.org/package/optparse-applicative) can [handle sub-commands](https://github.com/pcapriotti/optparse-applicative#commands). Relevant SO [post](https://stackoverflow.com/q/36339103/4051020)

**Comment by dopamane** [comment]
Also, restarting Z3 should happen automatically anytime it crashes, I do not think we should have a command for restart. If the user wants to restart, they should run `kore smt stop ; kore smt start`. However, I do think reinit should be a command (or part of a larger smt config command) so the reinit interval can be changed by the user as needed.

**Comment by dopamane** [comment]
How to identify database?  `kore start` outputs a DB name, what is the best way to save it in the environment for subsequent commands?
