### ISSUE TITLE
Don't wrap "bare" Map and Set terms

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2501]
"Bare" Map and Set terms (for example, functions) are wrapped [here](https://github.com/kframework/kore/blob/a4b771355cc2464c28a6a4144df7711d852bbbc2/kore/src/Kore/Builtin/AssociativeCommutative.hs#L229) with the internal structure that should be reserved for built-in Map and Set constructors. This should not happen.

**Comment by ttuegel** [comment]
In [`internalize`](https://github.com/kframework/kore/blob/e0614507f2172e8d161fa8e8eddd844dba724eae/kore/src/Kore/Builtin/Map.hs#L504) there is a lot of logic to work around the last case of `toNormalized`. So, we just shouldn't have that case in the first place.

**Comment by andreiburdusa** [comment]
I tried taking care of the case of sets first because it breaks less unit tests.

If we remove that last case of `toNormalized`, there will be a problem with set concatenation. For example, in the case of
```
                ( Mock.concatSet
                    (Mock.elementSet (mkElemVar Mock.xConfig))
                    (mkElemVar Mock.xConfigSet)
                )
```
`toNormalized` will be called recursively for each child, returning `Nothing` for the second, therefore making the whole result `Nothing`.
Allowing wrapping "bare" set terms if they are children of a concatenation leaves a singe broken unit test that I'm still investigating.

**Comment by ana-pantilie** [comment]
This was attempted but was not successful.
