### ISSUE TITLE
Correct encoding of ensures clause

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2593]
See kframework/k#1945.

The backend uses the correct interpretation of `ensures`, but the frontend encodes the rules the wrong way. We should:

1. Document the correct encoding.
2. Modify the backend to accept either encoding.
3. Modify the frontend to emit the correct encoding.
4. Forbid the incorrect encoding in the backend.

**Comment by ttuegel** [comment]
Actually, this one is not ready because we also need to change the LLVM backend.

**Comment by ana-pantilie** [comment]
We should see if we have to modify https://github.com/kframework/kore/blob/master/design-decisions/2020-05-02-function-rules.md as well.

**Comment by ana-pantilie** [comment]
@MirceaS Since this might be blocked for a long time, let's rename [toTermLike](https://github.com/kframework/kore/blob/d3b7bd2f6e53d590b7b04728dd776d5fe41ea5ac/kore/src/Kore/Equation/Equation.hs#L8) to `toTermLikeTODO` and `toTermLikeOld` to `toTermLike`. The reason for this is that I think that, currently, the names indicate that we'd prefer to use `toTermLike`, when that's actually not true because it isn't fully supported now.
