### ISSUE TITLE
kore-prof: Simple text report

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2704]
It is difficult to analyze large `kore-prof` reports with Speedscope because it cannot handle such large files. We should add an output mode for `kore-prof` which prints a table of entries with the name of each entry, the number of times it appears, and the total time spent in that entry. This would allow many hot spots to be identified without using Speedscope, but it would also allow users to easily narrow down their profile for better viewing in Speedscope.

**Comment by ana-pantilie** [comment]
Right now `kore-prof` is a wrapper around `eventlog2speedscope`. I believe this feature should be added directly to `kore-prof`, as this seems out of the scope of `eventlog2speedscope`. Is this what you had in mind as well?

**Comment by JKTKops** [comment]
When you typically use `kore-prof` on a semantics, do you find that the output information helps finding the bottleneck rules? Some clarity questions for this:
1) What does total time actually tell you? Self time seems much more relevant, but gathering self-time information seems harder.
2) If one _particular_ application (self-time/resulting simplification) of a rule is much slower than typical applications of that rule, what would that mean? Would you be able to tell that from this kind of profile?
3) When profiling semantics, it seems like [the information here](https://github.com/kframework/kore/issues/2682#issuecomment-864017268_) is what you are usually looking for. It seems to me like the eventlogs should have all the necessary pieces to extract this information, but I'm not sure that it would be present in this format. I'm not even sure how to read this information out of the speedscope profiles.

**Comment by ana-pantilie** [comment]
> What does total time actually tell you? Self time seems much more relevant, but gathering self-time information seems harder.

Why do you think self time is more relevant?
I think total time is pretty relevant as well, but maybe I'm wrong. If we could view each entry and its total time, if anything stands out, like simplifying a particular symbol application, we'd know where to look for possible inefficiencies.

> If one particular application (self-time/resulting simplification) of a rule is much slower than typical applications of that rule, what would that mean? Would you be able to tell that from this kind of profile?

I don't think we have any direct information on _rules_. We have information about the _terms_ which are simplified, and which symbol applications they have at the top.

> When profiling semantics, it seems like the information here is what you are usually looking for. It seems to me like the eventlogs should have all the necessary pieces to extract this information, but I'm not sure that it would be present in this format. I'm not even sure how to read this information out of the speedscope profiles.

That link doesn't work for some reason, so I'm not sure what information you're referring to.

> I guess it also matters if the goal here is to improve the ease of profiling Kore itself versus the ease of profiling a semantics.

Sorry, I don't really understand this. What do you mean by Kore vs semantics?

**Comment by JKTKops** [comment]
> Why do you think self time is more relevant?

My understanding, which could totally be wrong, is that total time includes all the time spent _under_ that symbol as well. For example, if we are trying to simplify a call to `+Bytes`, and one of the arguments is huge, then the `:simplify:Lbl'UndsPlus'Bytes'Unds'...` frame will include the time to simplify the large argument as well. Self time wouldn't. Maybe I don't understand this... or maybe I don't understand how to use total time information to find bottlenecks.

> We have information about the _terms_ which are simplified, and which symbol applications they have at the top.

In that case, I suppose the log entries PR will still be useful for obtaining information about particular rules. Identifying a function symbols which are problematic still narrows the problem down to only a handful of rules, so that's still useful I think.

> That link doesn't work

Should be fixed, it was supposed to link to the related discussion in #2682 where Everett specified which timing data we are looking for with log entries. I suppose that actually it would make the most sense if these different approaches both result in meaningful data. I think that from this information we can learn which symbols are hot more easily, while the log entry approach can give meaningful information about individual rules?

> Kore vs semantics

For example, maybe I think that one codepath through the simplification loop is slow (I don't know how this loop works, but just trying to make an example) so I write a proof that should use that codepath and then try to use `kore-prof` to compare that simplification step to other steps. In this case, I'm effectively profiling `kore-exec`. In Everett's use case, we'd be looking for specific problematic symbols, that is, we are profiling some specific semantics.

On second thought we are definitely trying to make it easier to profile semantics here, because if we were trying to profile `kore-exec` we wouldn't be using `kore-prof`, right? We'd be using `hs-speedscope` or other tools for heading the original eventlog.

In that case I wonder if we should (in a separate task) also consider making `kore-prof` output easier to read for users who don't understand how `kore` works. For example, add an option to de-munge labels, `Lbl'UndsPlus'Int'Unds'` => `+Int`.

Let me know if I'm misunderstanding anything. I think I might be misunderstanding how our profiling tools are meant to be used because I'm trying to come at it from the KEVM mindset.

**Comment by ana-pantilie** [comment]
> For example, if we are trying to simplify a call to +Bytes, and one of the arguments is huge, then the :simplify:Lbl'UndsPlus'Bytes'Unds'... frame will include the time to simplify the large argument as well.

I think if that's the case, then we'd have a similar entry for the top symbol of the huge argument, and we'd notice that there's a problem there.

After some thought, I'm not that sure anymore if self time is really that useful for profiling the semantics. I think it usually just means the backend is doing some work for which we don't emit events.

> In that case, I suppose the log entries PR will still be useful for obtaining information about particular rules. Identifying function symbols which are problematic still narrows the problem down to only a handful of rules, so that's still useful I think.

I think there is some confusion here. The log entry PR will help with identifying which _rewrite rules_ (axioms or claims) are problematic. The rules which apply to symbol applications are _function rules_ (equations), which we apply during simplification.

About Kore vs semantics, I understand now what you mean. `kore-prof` won't help you if you want to profile the backend itself. We have instructions to do that [on the wiki](https://github.com/kframework/kore/wiki/Profiling#haskell-profiling).
 
> In that case I wonder if we should (in a separate task) also consider making kore-prof output easier to read for users who don't understand how kore works. For example, add an option to de-munge labels, Lbl'UndsPlus'Int'Unds' => +Int.

This de-munging is effectively unparsing back to K, we'd need the frontend to provide us a tool to do that. Maybe `kast` would work, but I'm not really sure it's feasible.

**Comment by JKTKops** [comment]
> We'd have a similar entry for the top symbol of the huge argument, and we'd notice there's a problem there.

To notice that problem, you'd have to know that the top symbol of the huge argument appears under the call to `+Bytes`, which wouldn't be apparent in this text format, right? I suppose this format could help you identify _potential_ problems, which can then be investigated further with `--matching-children` and speedscope.

> Maybe `kast` would work

`kast` doesn't work, because most labels we would want to de-munge take arguments, and `kast` can't parse them if arguments aren't supplied. I agree it would make the most sense to get support from the frontend for that though, as implementing our own "label unparser" feels brittle.

**Comment by ana-pantilie** [comment]
Related to https://github.com/runtimeverification/haskell-backend/issues/3226, because we want to reimplement kore-prof anyway, this would be a nice feature to have.
