### ISSUE TITLE
Kore profiling discussion

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/haskell-backend#2747]
It would be very helpful to output enough information to figure out which node a log entry (in general) or at least `DebugTransition` and `DebugAttemptEquation` (in specific) are emitted from. That way we can then pull up that node in the kore-repl and then use standard (not oneline) logs to look at the term the equation is being applied to. Using standard logs on the entire proof is not really an option as it generates far too much output that is also quite a bit harder to process.

If there is a way to get `kore-repl` to select branch nodes the same way as `kore-exec` consistently, it's enough to attach a step number to log entries. Otherwise, a user needs the whole _path_ through the branch nodes so they can go the same way. I think one possibility would be to add a `DebugSelectNode` entry which emits a message like "selected node [DEST] from node [SRC]." Then a script that processes these log files could be modified without much trouble to output the path to take to get to a problem node (in fact, it could probably even output a viable `--debug-script` to get you there automatically).

**Comment by ana-pantilie** [comment]
I've been thinking about this for a while, and I think that, essentially, the problem is just that our `kore` configurations are really large and we just want to be able to compress and retrieve the configuration afterwards.

Off the top of my head, we could just associate ids to each configuration (hashing function maybe?), log the ids inside the `DebugAttemptEquation` one-line logs, and redirect the configurations to some other file where we have this `id -> configuration` table.

This might not be the best solution, but I think that this problem is what we should be focusing on, instead of trying to map `kore-exec` node ids to `kore-repl` node ids, for which I can't think of any general robust solution.

**Comment by JKTKops** [comment]
> we just want to be able to compress and retrieve the configuration afterwards.

What we really want is to be able to jump to that configuration in `kore-repl`. As long as it's possible to load the configuration from the table into the repl, that sounds like a good approach.

**Comment by ana-pantilie** [comment]
> What we really want is to be able to jump to that configuration in kore-repl.

What other information do we need such that using `kore-repl` is necessary?

**Comment by JKTKops** [comment]
We want to be able to get information from executing the next step, e.g. logs for specific equations (as opposed to whole transitions) but for that step only.

**Comment by ana-pantilie** [comment]
If we did https://github.com/kframework/kore/issues/2748, wouldn't the profile contain that information? Maybe we could emit an event at the top of the transition loop with the configuration id?

I'm trying to move away from using the `kore-repl` here, because I still don't think we can do the node/configuration mapping accurately with the way the things are now, we'd need to completely redesign the execution of `kore-exec` and `kore-repl`.

**Comment by JKTKops** [comment]
I think #2748 combined with a configuration ID would work.

If we want to be able to see the _exact_ term that it tried to apply an equation too (ala the DebugAttemptEquation entry) how would we map the profile entries back to the log entries (or just how would we get to that term at all, if there's another better way)? In the configuration at the top of the transition loop, the term may not even appear because it might only appear after some simplification has already been done.

**Comment by ana-pantilie** [comment]
> If we want to be able to see the exact term that it tried to apply an equation too (ala the DebugAttemptEquation entry) how would we map the profile entries back to the log entries (or just how would we get to that term at all, if there's another better way)? In the configuration at the top of the transition loop, the term may not even appear because it might only appear after some simplification has already been done.

That's a very good point.

This is a tricky issue, and I agree that it would have probably been ideal to able to inspect a particular step (which we identified as slow) in `kore-repl`. The interactivity makes finding the problem easier. I guess that a profile with all this information would easily get very cluttered and very hard to read.
We'd need to do https://github.com/kframework/kore/issues/2489 to be able to have this interactivity, though, and it would be a _very_ big change to the backend.

There might be another direction we could go, that of using structured logging. We have some infrastructure in the backend for creating a SQLite DB for the information we log during a run, which I don't think is used anymore (and I'm not sure if it ever was used?). I spent some time looking at this today, basically we create some tables for some of the log entries, and some tables for the datatypes we log in those entries, I believe. The information in the DB looks pretty incomplete, though, or maybe I'm not interpreting it right, but I guess it shouldn't be that hard to clean this up and add more entries since we already have the infrastructure in place.

What do you think, would having access to a log DB help? I'd imagine this could eventually be used to create a `kore-exec` specific profiling/execution-viewer tool.

**Comment by JKTKops** [comment]
A log DB could be helpful. What kind of information is in there?

At the end of the day, the problem that this issue identifies is enabling log entries for only a _specific_ step of the proof that we can identify as slow. The easiest way to do that initially seemed to be via `kore-repl` to me, but it doesn't have to be.

Depending on what's in that log DB, I'd agree that a kore-exec profiler is possible. Just from log entries that already exist, I believe it's possible to reconstruct the speedscope profile.

**Comment by ana-pantilie** [comment]
> What kind of information is in there?

I think it can be all of the information in the logs themselves. Currently, it basically looks like the following: for each log entry type we have a table and each row represents a specific logged event. Right now the information in the events themselves looks kind of broken but I'd imagine it could contain the timestamp and references to the data that it logged (like a `kore` term). Then there is one table for each type that was logged, and I noticed that one of these tables contained actual kore terms inside as rows.

**Comment by JKTKops** [comment]
That sounds like it could work. It might still be a lot of information to slog through, but if it's more organized than just a text file it would be much _easier_ to slog through.

Since `DebugAttemptEquation` is used both before and after, we'd even be able to identify the application that was slow, assuming we can query the DB for timestamps of sequentially logged entries. Having the term attached to that would, I think, solve the original goal.
