### ISSUE TITLE
Potential Performance Problem with LogicT

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/haskell-backend#2756]
It's a well-known potential performance problem in logic programming to frequently attempt to observe the branches and then scatter them back. This can cause quadratic slowdown. I've noticed we somewhat frequently seem to do
```hs
do ... <- Logic.observeAllT ...
   ...
   scatter ...
```
which could be causing slowdown. In the standup, we said we should look into this. I'm not _certain_ it causes a problem, because the real culprit tends to be `msplit`, and I don't think `observeAllT` is implemented in terms of `msplit`.

[This new package](https://hackage.haskell.org/package/logict-sequence) is supposed to not have this problem, but I don't know how it compares to `LogicT` otherwise.

**Comment by ana-pantilie** [comment]
> I'm not certain it causes a problem, because the real culprit tends to be msplit, and I don't think observeAllT is implemented in terms of msplit.

One place we use `msplit` is to implement [gather](https://github.com/kframework/kore/blob/f667127d026d52403789b19003d7bcacc2525329/kore/src/Logic.hs#L18), which is used to implement `MultiOr.gather` (which we sometimes call `OrPattern.gather` or `OrCondition.gather`). I don't think this is used in too many places, but we should still investigate if it's causing problems or not.

**Comment by alexd1971** [comment]
>performance problem in logic programming to frequently attempt to observe the branches and then scatter them back

Regarding this statement, it doesn't seem to be correct. After reading `logict` package documentation I could find out that we don't have two sequential actions: `observeAllT` and then `scatter`. We have `observeAllT` which runs `LogicT m a` computation which internally uses `scatter` function which has standart implementation described in quick start guide of `logict` package. So here we have merely standard documented usage of `LogicT` computations.

Looking at profiling results we can see the following:
```
82.7     -     -  Kore.Rewrite.Transition runTransitionT (31669)
79.0     -     -    Control.Monad.Logic observeAllT (20816833)
 3.7     -     -    Kore.Rewrite.Transition fmap (0)
   -     -     -    Kore.Rewrite.Transition >>= (0)
   ```

```
83.5    .3    .3  Control.Monad.Logic observeAllT (29606918)
62.9     -     -    Kore.Rewrite.Transition >>= (0)
13.3     -     -    Kore.Reachability.Prove transitionRule' (0)
 2.7     -     -    Control.Error.Util maybeT (7167366)
 1.5     -     -    Kore.Simplify.Pattern simplifyTopConfiguration (0)
 1.2     -     -    Kore.Internal.MultiOr foldr (4124848)
  .4     -     -    Kore.Rewrite.Step applyRemainder (5651)
  .3     -     -    Kore.Simplify.Simplify simplifyCondition (1054764)
  .3     -     -    Kore.Rewrite.SMT.Evaluator evalConditional (135031)
  .2     -     -    Kore.Simplify.Application makeExpandedApplication (1770146)
  .2     -     -    Kore.Internal.Condition forgetSimplified (0)
  .1     -     -    Kore.Internal.MultiAnd foldr (670212)
   -     -     -    Kore.Rewrite.Transition fmap (0)
   -     -     -    SMT pure (0)
   . . .
```
The most significant contribution into overall performance `observeAllT` function has when it internally called in `runTransitionT` And obviously this contribution is reasoned by a huge amount of invocations because individual `observeAllT` contribution is negligible.

So probably here, using `logict` package, further optimisation is possible only if we could change logic somehow to get less amount of `observeAllT` invocations. At best it is not obvious how to do and at worst it is not possible at all.

Looking at [recommended replacment package](https://hackage.haskell.org/package/logict-sequence) for `logict` we see:

> Provides a variant of the LogicT monad that should have asymptotically better performance when frequently observing results. 

So probably it's our case. And replacing package may give us performance improvements.
