### ISSUE TITLE
Timeout stuck proofs

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#2847]
I'd like to provide a timeout per symbolic-execution spec when invoking the Haskell backend. For example, if I do `--max-step-time 10`, and a step `A => B` takes 11s, I would like it to halt execution, and print out the state `A`.

This will assist us in finding "slow" proof steps, that we likely need to simplify some component of the state that is `A`.

It will also provide the intermediate state `A`, which we can now test that it makes 1 step of symbolic execution (instead of everything leading up to it) for creating a minimal example.

**Comment by ana-pantilie** [comment]
Is this for `kore-exec` or for `kore-repl`?

**Comment by ehildenb** [comment]
For `kore-exec` I guess, but I'm not sure why it would be different?

**Comment by ana-pantilie** [comment]
I believe it's very different because of the way `kore-exec` handles making execution steps. I remember I thought about this for a while when you opened the issue and it seemed like we'd have to probably rewrite a lot of our proof strategy code to make this work.

For `kore-repl`, it should be fairly simple I think.

Stepping back a bit, I think that both this issue and https://github.com/kframework/kore/issues/2848 will be trivial once we do https://github.com/kframework/kore/issues/2489 (from Bogdan's list of product ideas people voted for). This is a very big change, though, so it will take a while.
