### ISSUE TITLE
Investigate Haskell benchmark libraries

### ISSUE THREAD

**Issue by dopamane** [runtimeverification/haskell-backend#2918]
We should investigate using Haskell benchmark libraries to analyze performance. Currently we gather performance statistics by running integration tests. A benchmark library like [criterion](https://hackage.haskell.org/package/criterion), [gauge](https://hackage.haskell.org/package/gauge), [tasty-bench](https://hackage.haskell.org/package/tasty-bench), etc. would let us monitor the performance of specific Haskell functions and algorithms.

**Comment by ana-pantilie** [comment]
According to this year's [Haskell survey](https://taylor.fausak.me/2021/11/16/haskell-survey-results/), Criterion is most widely used.

I haven't used benchmarking libraries before, so right now it's not clear to me even what Criterion _does_. I'll keep reading, though, and let's add any insight we have to the issue.

**Comment by ana-pantilie** [comment]
I found [Criterion's tutorial](http://www.serpentine.com/criterion/tutorial.html), which has been pretty useful for getting a broad understanding of what it does, and with this a realization about the actual _purpose_ of benchmarking our project.

It seems to me like the traditional usage of benchmarking is for comparing different solutions to the same problem. So, for this to make sense to our project we'd need another version of a symbolic execution engine for K to compare ours to. This could be the Java backend, but unless it already has some similar benchmarking done, we would have to first benchmark that using similar methods. I don't think it currently does, since our method of comparing the two backends has always been by comparing run time on the KEVM proofs. I'm not sure I see a lot of value in spending time to create more complex benchmarks for the Java backend.

Now, maybe we don't want to do that, but I think we could we use these techniques to check for regressions when making changes to our project. Judging by the tutorial, we could try to benchmark some of our unit tests. Actually, we should probably write separate unit tests for the benchmarks. Note, that to do this on CI, we'd need to run them separately, on a machine with low contention, to get accurate results. The fact that we could test for performance regressions in _separate_ components of the backend sounds very enticing to me. A script could deploy the HTML report generated for the feature branch, and we could manually compare that to the master HTML report.

Does this sound do-able, or am I missing some important details?

**Comment by Bodigrim** [comment]
As an author of `tasty-bench` I'm obviously biased, but I think it is better suited for performance regression tracking than `criterion` / `gauge`. You can save baseline measurements with `--csv`, and then feed them back with `--fail-if-slower` key, allowing `tasty-bench` to highlight benchmarks which became slower than baseline. No need to compare reports manually. More details: https://github.com/Bodigrim/tasty-bench#comparison-against-baseline

**Comment by ana-pantilie** [comment]
Thanks for the suggestion @Bodigrim ! That does sound more in line with what we're looking for, so we'll definitely take a look. 😄

**Comment by ana-pantilie** [comment]
We're getting better information from benchmarking integration tests. We would benefit from having more semantics to test with.
