### ISSUE TITLE
Print substitution for final implication

### ISSUE THREAD

**Issue by dopamane** [runtimeverification/haskell-backend#2927]
@ehildenb [on Slack](https://runtimeverification.slack.com/archives/CC360GUTG/p1638179874206300) asks:

Is it possible to have the haskell backend print out the substitution for the final implication check? That is, if you have:

```
claim LHS => RHS requires REQ ensures ENS
```

And we've reached a state `FINAL_STATE` such that `RHS` matches `FINAL_STATE`, and the `REQ` and `ENS` clauses hold, I'd like to know the substitution that `RHS` matches `FINAL_STATE` with. Is it possible or easy?

Maybe there is already a logging option for it?

**Comment by ana-pantilie** [comment]
The kore-rpc server does this, but the input is restricted to a certain form. In order to do the same for kore-exec, we have found that returning such a substitution is incompatible with our current algorithm. We would need to redesign check implication with this requirement in mind.

Relevant code: https://github.com/runtimeverification/haskell-backend/blob/39eaeb84601d5934bf4a5cfc9c977bdd04c4f016/kore/src/Kore/Reachability/Claim.hs#L727-L737
