### ISSUE TITLE
Optimize semantic rule application

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2969]
All semantic rules have to be unified with the configuration when rewriting. Since very few rules actually apply each step, @ehildenb suggests we attempt unification first on the `k` cell (and, in general, this heuristic could be provided by the user) and only if that succeeds we continue unification on the bigger problem.

We need to test this out, and measure performance to get an idea how helpful it would be to optimize the unification algorithm.

Also, note that function definition rules use unification as well. I make the changes described above only for applying semantic rules.

**Comment by ana-pantilie** [comment]
We need to measure how much time is spent in semantic rule application, specifically the unification phase.

One idea is to log before and after attempting unification, here: https://github.com/runtimeverification/haskell-backend/blob/bcb605bf1980d621a83126fa438621c4d0e5cf37/kore/src/Kore/Rewrite/Step.hs#L152

Log entries: `DebugSemanticRuleUnificationStart` and `...End`, with one-line entry format containing source location of rule.

The timestamps should give us timing info.

**Comment by ana-pantilie** [comment]
Move back to triage after we get ^ done.

**Comment by dwightguth** [comment]
I discussed this idea with Everett a bit, and my gut feeling is that done properly, you ought to be able to get very similar performance gains to what you describe that are actually global to /all/ cells, not just the k cell, for most, but not all, rule applications by making use of functionality provided by the llvm backend.

A little background:

If you run `kompile -O3 --backend llvm`, the llvm backend will generate, in addition to the usual decision tree that is used to apply top-level rules, **specialized decision trees** where it takes into consideration information from the rhs of the rule that previously applied in order to avoid doing as much pattern matching. One way it does this is by removing rules that /cannot/ apply to any term that might be created by applying a substitution to the right hand side of the previous rule.

While making use of these decision trees themselves is likely to be difficult since you need unification and they were explicitly designed with pattern matching in mind, it ought to be very easy to add a parameter to the decision tree generator in the llvm backend to tell it to generate, instead of a decision tree for each rule rhs, a set of rules that *might* apply next. The meaning of this set is that this is the exhaustive set of all rules that you need to try; any rule not in the set can be safely assumed to not apply to this term.

Once you have this set for each rule, you would just need to store with each top-level configuration a unique identifier for that set that can be used to look up the set of rules that need to be tried. Then, instead of trying all the rules on each configuration at each step, you can just look at each configuration, look up the set of rules that configuration needs to try next, and try only them.

Bear in mind that this is not a fool-proof replacement for proper indexing, and some kind of separate indexing mechanism might not be a bad idea. In particular, consider the following rule:

```
rule <k> foo => . ...</k>
```

When compiled, the right hand side of this rule will have a k cell containing nothing but a variable. As a result, the set of rules that can apply next is still the set of all rules in the definition.

I have a feeling that this could be implemented relatively easily though and provide some substantial improvements for relatively little development effort. Worth considering.

**Comment by dwightguth** [comment]
If you are interested, here's what my idea would involve technically:

1. Making a change to the llvm backend. The code in question lives in the `matching` directory and is written in scala. The entry point is in Matching.scala. You would want to create a new entry point that does the following:
   * Parses the kore definition
   * Constructs the `axioms` and `symlib` objects the same as the existing entry point
   * modify mkSpecialDecisionTree to split it into two functions. One that returns a Matrix, and one that does the final `if` block of the existing function.
   * Call the first of those two functions on each axiom, similar to what is done in Matching.scala already. Since you get back a matrix instead of a decision tree, you would not serialize the decision tree to a file, however.
   * Once you have the matrix, you could call something like `matrix.rows.map(_.clause.action.ordinal)` to get the set of rules that would be possible to apply after the axiom you are currently processing.
   * then you just need to serialize it to disk somehow for the haskell backend to read back in later.

Of course, you would need to be able to translate between "ordinals" and actual axioms. The ordinal though is nothing more than a 0-based index of the axiom within a KORE definition in the orders they appear in the file.

**Comment by ana-pantilie** [comment]
### How to add log entries for the Haskell backend:

We organize log entry types as follows: in https://github.com/runtimeverification/haskell-backend/tree/master/kore/src/Kore/Log we have a module for each entry type.
Each type should be made an instance of `Pretty` and `Entry`. The type then needs to be added to the [registry](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Log/Registry.hs).

That's pretty much it. See `kore-exec --help` for information on how to log certain information. The option `--log-entries LogType1, LogType2...` will be most helpful for this issue, it filters the logs and only prints out the entries of the mentioned types.

### The info that needs to be logged
The `rule` type mentioned in the above comment will, concretely, have as representation either a [ClaimPattern](https://github.com/runtimeverification/haskell-backend/blob/bcb605bf1980d621a83126fa438621c4d0e5cf37/kore/src/Kore/Rewrite/ClaimPattern.hs#L98) or a [RulePattern](https://github.com/runtimeverification/haskell-backend/blob/bcb605bf1980d621a83126fa438621c4d0e5cf37/kore/src/Kore/Rewrite/RulePattern.hs#L194). The `attributes` field of each of these contains the `SourceLocation` attribute. The `unifyRule` function might need to be given the information that any instances of `rule` should contain this `SourceLocation` attribute. One solution would be to use https://github.com/runtimeverification/haskell-backend/blob/bcb605bf1980d621a83126fa438621c4d0e5cf37/kore/src/Kore/Rewrite/RewriteStep.hs#L198.

### Explanations for the above
Claims are the rules we add to `-spec.k` files and are the goals we want to prove. They can be applied coinductively to the configuration, as described in the literature on reachability logic.

Axioms are the rewrite rules we write when writing semantics in K. These are rules which describe the transitions inside the system. Note that K rules for symbols with the `[function]` attribute are not considered "rewrite rules" but equations, and they're irrelevant to this issue.

During execution the Haskell backend does the following: it attempts to apply the available claims, and then attempts to apply the axioms. Applying means attempting to unify the left hand sides of the claims/axioms to the current configuration in order to make a step in the proof.

The internal representation of claims is `ClaimPattern`. There are multiple types for claims (`AllPathClaim`, `OnePathClaim` etc.) but all of these are equivalent in the sense that they have the same representation.

The internal representation of axioms is `RulePattern`. I think we use the `RewriteRule` newtype a lot.

Let me know if you have any questions!

**Comment by dwightguth** [comment]
Please let me know when you have a version of the tool that can be used to take these measurements. I would like to measure it on my in-progress c semantics code, which is still extremely slow currently.

**Comment by ana-pantilie** [comment]
@jberthold if you have time, please go through the discussion on this issue. I have a feeling that the work you did on investigating if unifying the `k` cell first would improve performance heavily discounts any impact this work might have.

**Comment by jberthold** [comment]
> We need to measure how much time is spent in semantic rule application, specifically the unification phase.
 
An experiment with the evm-semantics was done in #3167, and the tool integrated in #3187. It shows that unification already fails very quickly (~28.16μs in the measurement) without a "fast path".

What is suggested by @dwightguth above is to use precomputed information to discard rules that can never apply. This might have some value but we would need to thread the (index into a) rule blacklist through from one rewrite step to the following, and need to perform the lookup by a rule name or index within a time shorted than reaching unification failure (which is in the area of ~30-40 μs). The winnings would probably be minor IMHO, suggest to close this.
