### ISSUE TITLE
CheckImplication and calls to the simplifier

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#2977]
The `CheckImplication` transition in our reachability loop contains some awkward calls to the simplifier:

- it constructs this `TermLike` with `mkIn` at the top (so it should actually be a `Predicate`) and calls the `Pattern` simplifier on it https://github.com/kframework/kore/blob/272a2e528bd556b15d12f29de9c779de0c6d7a54/kore/src/Kore/Reachability/Claim.hs#L554
- it calls the `Exists` simplifier directly https://github.com/kframework/kore/blob/272a2e528bd556b15d12f29de9c779de0c6d7a54/kore/src/Kore/Reachability/Claim.hs#L563
- it calls the `Not` simplifier directly https://github.com/kframework/kore/blob/272a2e528bd556b15d12f29de9c779de0c6d7a54/kore/src/Kore/Reachability/Claim.hs#L570

For the `mkIn`, I know that we do that in order to unify the two arguments. What we do here depends on answering the question: do we want simplification to call unification as it does now? If yes, the change here should be to create a `Predicate` instead of `TermLike` with `\\in` at the top. If not, we should call the unification procedure directly.

The other direct calls to the simplifier are a product of the leaky abstraction the current simplifier has. They should be replaced with calls to the Pattern simplifier.

**Comment by JKTKops** [comment]
The first bullet point was a simple change and was fixed in #3009.

The other two are more complicated. It should be that we just want to construct a particular pattern (`#Not { #Exists X1. #Exists X2. ... }`) and call the simplifier on that. However, using `mkExistsN` and calling the simplifier on it appears to behave differently than using `Exists.makeEvaluate` with a list of bound variables. I haven't been able to track down why, and at this point we want to move on from this issue for now.
