### ISSUE TITLE
Investigate new profiling options

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3008]
~Blocked on `co-log`.~

- [ ] Build with GHC 9.2.3, open branch with this experimental version
- [ ] Investigate the ghc-debug package

**Comment by goodlyrottenapple** [comment]
there is now a bytesmith PR adding support for GHC 9.2 https://github.com/byteverse/bytesmith/pull/23

**Comment by goodlyrottenapple** [comment]
Graphviz seems to also need this PR merged for GHC 9.2 support https://github.com/ivan-m/graphviz/pull/53

**Comment by goodlyrottenapple** [comment]
I've added a preliminary document outlining the profiling options for haskell programs here https://github.com/runtimeverification/haskell-backend/blob/ghc9/docs/profiling.md

since there are many options and tools, please let me know what to focus on when writing this up. I would like this to be a useful lookup guide when we want to do profiling

**Comment by ana-pantilie** [comment]
Check the error in speedscope to figure out what is going on with kore-prof on this version of GHC.
