### ISSUE TITLE
Proofs that reach RHS at depth bound are not discharged

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3035]
With this definition:

```
module TEST
    imports BOOL
    imports INT

    configuration <k> $PGM:Int </k>

    rule <k> X => X +Int 1 ... </k> requires X <=Int 10

endmodule

module TEST-SPEC
    imports TEST

    claim <k> 0 => 3 ... </k>

endmodule
```

I run:

```
export KORE_EXEC_OPTS='--bug-report bug'
kompile --backend haskell test.k --main-module TEST --syntax-module TEST
kprovex test.k --spec-module TEST-SPEC --depth 3
```

And I get:

```
<k>
  3 ~> _DotVar1 ~> .
</k>
```

But I expect `#Top`.

Are we not checking the final implication at the depth bound? Maybe it's for the same reason we don't prune branches in the kore-repl which are infeasible before the user steps into those branches?

I've attached a bug report.

[bug.tar.gz](https://github.com/runtimeverification/haskell-backend/files/8491591/bug.tar.gz)

**Comment by ehildenb** [comment]
This is causing situations in the summarizer where the proof is not discharged and it should be, because we symbolically execute basic blocks directly. It doesn't affect overall soundness, but leaves the user with a sense of overwhelming dread as they think that they haven't discharged the proof on that branch.

The workaround is to execute for one more step.

**Comment by ana-pantilie** [comment]
This is because one rewrite step is comprised of the following transitions internal to the backend:
https://github.com/runtimeverification/haskell-backend/blob/e56004ded38532213aaa3d6986dd24d97e299b12/kore/src/Kore/Reachability/Claim.hs#L374

What happens here specifically is in the second to last step `ApplyAxioms` will rewrite the configuration to `3`, and the next rewrite step will discharge the goal as proven in `CheckImplication`.

I believe documenting this better would be best, so that users understand the behavior better. The current behavior is optimal performance-wise. What this means is that during a rewrite step `CheckImplication` must come first, before applying claims and axioms. We could add another `CheckImplication` transition right at the end, but it would end up duplicating work in the general case, so it wouldn't be efficient to do that.

**Comment by JKTKops** [comment]
When using a depth bound, I think it should be possible to just add one `CheckImplication` transition only on the last step. The depth bound tells us when to stop, so it must be available somewhere. I'm going to take a look at this.
