### ISSUE TITLE
kprove fails to prove claim where circularity can apply at first step (but can still take a semantic step)

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/haskell-backend#3074]
I think this claim should succeed.
First, the claim cannot be applied as a circularity, so a semantic step must be taken, reaching `<k> foo(N - 1) </k> #And N > 0`.
This  partially unifies with the RHS of the claim, leaving `<k> foo(N-1) </k> #And N > 0 #And not(N-1 == 0)` to be proved.
This unifies completely with the LHS of the claim, so applying it as a circularity it should succeed.
 

```
$ cat test-helpers.k
module TEST-HELPERS
    imports INT

    syntax KItem ::= foo(Int)
    rule <k> foo(I) => foo(I -Int 1) </k>
endmodule


$ kompile --backend haskell test-helpers.k
[Warning] Compiler: Could not find main syntax module with name
TEST-HELPERS-SYNTAX in definition.  Use --syntax-module to specify one. Using
TEST-HELPERS as default.


$ cat test-spec.k
module TEST-SPEC
    imports TEST-HELPERS

    claim [reaches-zero]:
        <k> foo(N) => foo(0) </k>
      requires N >Int 0

endmodule


$ kprove test-spec.k
kore-exec: [163907] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The proof has reached the final configuration, but the claimed implication is not valid. Location: /home/user/erc20-verification/haskell-test/test-spec.k:5:9-6:24
  #Not ( {
    N
  #Equals
    0
  } )
#And
  <k>
    foo ( N ) ~> .
  </k>
#And
  {
    true
  #Equals
    N >Int 0
  }
  ```

**Comment by ehildenb** [comment]
I think I am seeing the same problem manifest in the KEVM summarizer when attempting the verify the generated claim for the basic block of a small loop.

I think it perhaps has to do with the heuristic that the Haskell backend uses to determine when it should stop and check for subsumption into the RHS of the proof. Because the terms are "similar enough" (perhaps because they only differ on function positions, but not constructors), it is trying to check subsumption into the RHS at step 0. This heuristic is to make sure that the backend stops when it gets to a state that is similar enough to the final state of execution, but here it's stopping this proof (and my proof) from even taking a single step.

I wonder if we can pass an option to the backend `--min-depth` which says "we don't want to check subsumption into the RHS of the claim until at least this many steps". This would actually make many executions that we have to do in the summarizer faster, because we already know the exact depth counts we need to execute to, so we can skip implication checking until the very end.

I would suggest that default min-depth should be 1, and you would have to set `--min-depth 0` to get that behavior.

**Comment by nishantjr** [comment]
Changing the semantics to:

```
module TEST-HELPERS
    imports INT

    syntax KItem ::= "noop"
    rule <k> noop => .K ... </k>

    syntax Pgm ::= foo(Int)
    rule <k> foo(I) => noop ~> noop ~> foo(I -Int 1) ... </k>
endmodule
```

and the claim to:

```
module TEST-SPEC
    imports TEST-HELPERS

    claim [reaches-zero]:
        <k> foo(N) => noop ~> foo(0) </k>
      requires N >=Int 0
endmodule
```

still causes things to get stuck too early:

```
$ kprove njr-test/test-spec.k
kore-exec: [171561] Warning (WarnStuckClaimState):
    (InfoReachability) while checking the implication:
    The proof has reached the final configuration, but the claimed implication is not valid. Location: /home/user/erc20-verification/njr-test/test-spec.k:7:9-8:25
  #Not ( {
    0
  #Equals
    N +Int -1
  } )
#And
  <k>
    noop ~> foo ( N +Int -1 ) ~> .
  </k>
#And
  {
    true
  #Equals
    N >=Int 0
  }
```

The `--min-depth 1` option won't be enough in this case (we'd need something like `--min-depth 3`).
The error message is also very confusing, "The proof has reached the final configuration, but the claimed implication is not valid",
making me thing that it stopped rewriting due to getting stuck in a "final" configuration.

**Comment by ehildenb** [comment]
Hmmmm, I guess the `--min-depth` option will solve my problem, but not the general problem.

Is there a use-case where we cannot compute the min-depth needed ahead of time?

**Comment by nishantjr** [comment]
@ana-pantilie is there a way to disable this heuristic? I'm actually not sure how I can prove this claim (or something similar) without disabling it.
