### ISSUE TITLE
Compact error/segmentation fault

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3077]
```
$ /Users/anapantilie/RV/haskell-backend/.build/kore/bin/kore-exec ./demo-kompiled/haskellDefinition.bin --module DEMO --pattern .krun-2022-05-30-21-24-31-rUHXdqwjRD/tmp.in.QZx08RsJH8
[1]    9547 segmentation fault  /Users/anapantilie/RV/haskell-backend/.build/kore/bin/kore-exec  --module DEM
```

```
$ /Users/anapantilie/RV/haskell-backend/.build/kore/bin/kore-exec ./demo-kompiled/haskellDefinition.bin --module DEMO --pattern .krun-2022-05-30-21-24-31-rUHXdqwjRD/tmp.in.QZx08RsJH8
Invalid non-NFData closure (type 818185033) in Compact
kore-exec: [6753] Error (ErrorParse):
    Failed to import compact
```
[kore-exec.tar.gz](https://github.com/runtimeverification/haskell-backend/files/8800179/kore-exec.tar.gz)

- [x] #3085
- [x] #3086

**Comment by dwightguth** [comment]
I think I know what is causing this. Let me explain the sequence of steps I took to reproduce the issue:

1. Install the kframework 5.3.65 ubuntu package for focal
2. Check out the `_update-deps_runtimeverification_k` branch of the haskell backend
3. cd to `test/owise-1` and run `make test`

This does in fact fail. But it's not a bug in the haskell backend, it's a bug in the test harness. The issue is that `kompile` now runs `kore-exec --serialize` to emit the serialized `haskellDefinition.bin`. However, due to how the test harness is written, it is using the version of `kore-exec` which is on the PATH, i.e., the version built via the kframework ubuntu package. We then pass --haskell-backend-command to krun, but this points us to a kore-exec which is a different binary than the one which generated `haskellDefinition.bin`. This is entirely unsupported by the compact library and as a result, tends to either segfault or otherwise behave very unpredictably.

I tested that if I ran `kore-exec definition.kore --serialize --module DEMO --output haskellDefinition.bin` from within `demo-kompiled` using the same version of `kore-exec` which we pass via `--haskell-backend-command`, then subsequent invocations of `make test` are passing again.

Unfortunately, I'm not entirely sure how to make the validity check we do on `haskellDefinition.bin` more robust in order to prevent this sort of thing. Maybe someone has an idea, but we may simply have to tell people if this occurs to double check that they are using the same version of kore-exec for both `kompile` and `krun`. In the meantime, we should probably add the `--haskell-backend-command` flag to kompile if we intend to run `krun` this way.

**Comment by dwightguth** [comment]
What you suggest could work as a validation mechanism. Right now we call `writeCompact` and `unsafeReadCompact`. Instead we could call `hPutCompact` and `hUnsafeGetCompact` and just write the file hash immediately prior to calling `hPutCompact`. We would have to slightly tweak the code that checks whether a file is a Compact during deserialization, but that wouldn't be much of a change.

I'm fairly sure that the issue we are seeing in the PR Ana mentioned is definitely due to a usage error. Whether the other instances of the same error are caused by the same issue isn't entirely clear, but I would definitely suggest we try beefing up the validation the way you suggest before we try a completely different approach to serialization.

**Comment by ana-pantilie** [comment]
@jberthold suggests to have my own type which puts together the program hash and the serialized data and define a Binary instance for that.

**Comment by goodlyrottenapple** [comment]
So after some investigation along with @PetarMax, it appears that the issue might not simply be a mismatch between `kore-exec` binaries, or at least that's not the only issue. We have tested and confirmed that the calls to `kompile` and `krun` on my M1 machine used the exact same version of `kore-exec`, still resulting in failure

```
Invalid non-NFData closure (type -1459441397) in Compact
kore-exec: [15377] Error (ErrorParse):
    Failed to import compact
Created bug report: kore-exec.tar.gz
[Error] krun: Backend crashed during rewriting with exit code 1
```

**Comment by ana-pantilie** [comment]
After implementing the executable hash check, see if the issue above is specific to M1 macs, if yes, just disable serialization on M1 macs for now.

**Comment by ana-pantilie** [comment]
Closing this because we have improved the error message for the case when the executables differ and the frontend provides an option to disable serialization.
