### ISSUE TITLE
Parallel build of kore libraries

### ISSUE THREAD

**Issue by radumereuta** [runtimeverification/haskell-backend#3080]
Currently, on my machine (AMD 5950x 16c32t) it takes `3m15s to build the haskell backend from a clean state.
With `ghc-options: -j` that dropped to ~2m25s.
Can we improve on this even more?
Maybe break up some dependencies in the code to allow GHC to parallelize even more?

P.S. The linked PR tried to add the `-j` option but CI broke for some reason. Local builds were fine.

**Comment by dwightguth** [comment]
I doubt we can improve much on the 2m25s time. The reason why it doesn't parallelize more than it already does is that if module A in Haskell depends on module B, then module B must be compiled first. This severely limits the amount of parallelism that is even theoretically possible, and reorganizing the code might not help much. Everett did comment that the haskell backend sometimes has a tendency to rebuild more than it really needs to on incremental builds, though, and it's possible that breaking the haskell backend down into separate cabal packages might help with this somewhat. That would not improve the build-from-clean time much though.

I know it's unpleasant, but haskell's tooling just kinda sucks. Maybe Serokell might have some other ideas, but we also might just be stuck.

**Comment by ana-pantilie** [comment]
Things to check:
1. see if the linked PR is still failing
2. are the Haskell backend executables being built sequentially? can they be built in parallel?

Idea for the future: not use Maven as much, use Nix instead? This would be a bigger task.

**Comment by radumereuta** [comment]
This was mitigated by #3083 but recent changes make it so a clean build takes over 3 minutes again.
I'm reopening this to explore more ways of improving the compilation time.

**Comment by ana-pantilie** [comment]
@radumereuta You can try `mvn package -Dstack.extra-opts='--fast'`. Re-open the issue if this is still a problem.

We need to figure out a way of building K so that builds are cached. If you're not modifying the Haskell backend when re-building, then it shouldn't recompile it. Nix, or a Nix-like build cache should be used.

**Comment by ana-pantilie** [comment]
@radumereuta You can try `mvn package -Dstack.extra-opts='--fast'`. Re-open the issue if this is still a problem.

We need to figure out a way of building K so that builds are cached. If you're not modifying the Haskell backend when re-building, then it shouldn't recompile it. Nix, or a Nix-like build cache should be used.

**Comment by radumereuta** [comment]
That's just a tradeof. With optimizations:
```console
$ mvn package -DskipTests
[INFO] K Framework Haskell Backend ........................ SUCCESS [03:08 min]
$ time make -j 32 -O regression-new
real	1m59,043s
```
Without optimizations:
```console
$ mvn package -DskipTests -Dstack.extra-opts='--fast'
[INFO] K Framework Haskell Backend ........................ SUCCESS [01:10 min]
$ time make -j 32 -O regression-new
real	3m56,855s
```
For my workflow, I'm just moving the time from compilation to running tests. Which also makes the testing inconsistent and non-representative of the final version.
I would appreciate it if we could at least discuss possible solutions with the Serokell guys. Maybe they have some simple ideas.
If it turns out it's too complicated, then we can give up on this and look into caching.
Please reopen if you think this is reasonable to achieve.

**Comment by ana-pantilie** [comment]
I mean, if you're not modifying the backend then it _should not_ be rebuilt. Even if you were modifying it, the Haskell compiler would not rebuild the whole thing every time. It seems to me like the issue you're having is actually caused by K's build system.

On our side, we can, and will continue to try to improve build times. We do not, however, expect those improvements to be radical.

**Comment by radumereuta** [comment]
Apparently, you can use `mvn clean -Dhaskell.backend.skip` and it will not touch the Haskell code.
This alleviates a bit my issues with the long haskell-backend long compile time.
