### ISSUE TITLE
Serokell: hashing is a top consumer

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3113]
We found that the cache in attemptEquation enjoys the hit ratio of over 95%, so it is well-placed. However, the lookupCache is expensive because a lot of time is spent hashing and comparing keys.

Suggestion:
1. compute the hash in advance
2. investigate using a different datastructure for less comparisons (like a trie)

**Comment by ana-pantilie** [comment]
For this issue, please prioritize providing some ideas and documentation for how to tackle this issue.

**Comment by dcastro** [comment]
Here's a summary of what we've tried:

* Replacing `HashMap` with a trie map, see the branch `diogo/#3133-cache-hit-ratio-trie`. It didn't have a noticeable impact on performance, possibly due to the need to "linearize" the key.
* Replacing `HashMap` with a `Map`, resulted in performance degradation.
* Avoiding computing an `Equation`'s hash more than once. Negligible impact, 0.93% overall speedup.
* Avoiding computing a `TermLike`'s hash more than once, see the branch `diogo/#3113-cache-hit-ratio-terms`. Negligible impact, 0.33% overall speedup.

There's also an ongoing attempt to store the hash of each `TermLikeF` node in the corresponding `TermAttributes` in the branch `jb/caching-termlike-hashes`.

**Comment by dcastro** [comment]
A couple more details about `jb/caching-termlike-hashes`:

We ran our benchmarks against ebd826f19869725d887de3a99a727cfd97dad470 (using ac0e3c0c403bbca4d812d921f8783f4dfcdbcb29 from master as a baseline). 47 benchmarks succeeded, 23 crashed (most with an "Invalid map: duplicated keys" error).

Considering only the 47 successful benchmarks: 

* Total runtime using an executable built from the target branch: 9451.694s
* Total runtime using an executable built from the baseline branch: 10065.793s
* 9451.694 / 10065.793 = 0.938991493, so a ~6.1% overall speedup.

The results look promising, but at this point, it's not yet known whether this approach is feasible without breaking correctness.

**Comment by ana-pantilie** [comment]
@goodlyrottenapple points out that there might be other subtle bugs created by not updating attributes (like the `Simplified` attribute) in other situations. This is related to doing optimal hashing (if we continue on the path @jberthold started).

**Comment by ana-pantilie** [comment]
Relevant branch with in progress work: https://github.com/runtimeverification/haskell-backend/commits/jb/breakerzirconia/caching-termlike-hashes

**Comment by treeowl** [comment]
I've taken a look at the draft implementation, and I have a few concerns.

### Salt
The approach to salting is bogus. That might be okay, but I don't know enough about how the `Hashable` instance is used to say. If it's just used for `HashMap`, then something bogus is fine (though we might want to tweak things slightly for better performance). Similarly, as long as we're not using anything that truly relies on salting for correctness, and collisions are rare enough not to hurt performance too badly, then something bogus is fine as well. Is this the case?

### `Generic` instance

The derived `Generic` instance (and the `SOP.Generic` instance it feeds into) can easily defeat the hash  invariant if used the "wrong" way. My understanding is that these instances may be used only for their `from` method (to implement test diffs and the like), in which case it's fine, but makes me nervous.

### `Corecursive` instance

This is a bigger can of worms, and I suspect `traverseVariables` (at least) is broken by its use. The trouble is that `embed` blindly combines `TermAttributes` with `TermLikeF`, without having any idea whether the cached hash in the `TermAttributes` is the hash of the `TermLikeF`. Some possible approaches to improving the situation:

#### 1

Just be more careful about using `embed` for `TermAttributes`. That's the "simplest" thing, but it seems error-prone. Any overly polymorphic `recursion-schemes`-based code will break, and it seems tricky to find potential breakage points.

#### 2

Attach the hash more firmly to `TermLikeF`. There are a few ways this might be done, none of which is entirely trivial. The most direct option would be to make `TermLikeF` a wrapper around a `TermLikeF'`. Doing only this would add a fair bit of indirection, which is undesirable. However, we could get rid of that by using a custom type instead of `CofreeF` to define `TermLike`.

```haskell
newtype TermLike variable = TermLike
  { getTermLike :: BaseTermLike variable (TermLike variable) }
data BaseTermLike variable child = BTL (TermAttributes variable) {-# UNPACK #-} !(TermLikeF variable child)
data TermLikeF variable child = TermLikeF Int !(TermLikeF' variable child)
```

Now we can define pattern synonyms for `TermLikeF` that maintain the hash invariant. Sadly, GHC still doesn't allow pattern synonyms to have different constraints for matching than for construction, so we'd end up with `Hashable` constraints even where we don't really need them. Perhaps that's a price worth paying.

#### 3

Make `embed` maintain the hash cache invariant, and perhaps stop using the `TermLike` constructor directly in general. This would make `embed` more expensive, since it would (shallowly) calculate the hash of the `TermLikeF`. As long as we don't do a whole lot of `TermAttributes` editing in `TermLike`s without also editing the `TermLikeF`s, this shouldn't be a big deal. I do see at least one spot where a bit of such editing happens: `updateCallStack`. In that particular spot, recalculating the hash would definitely be redundant and therefore undesirable.

**Comment by treeowl** [comment]
I think approach (3) above is really the one to beat. It restricts hash variant maintenance to just a couple places, and it doesn't break the use of polymorphic traversals and such on the base functor.

**Comment by jberthold** [comment]
You are definitely right about the salting issue in the current draft. This code branch started as a quick time-boxed hack for an afternoon to see how much I would get done and what the profiles would look like.

I like the idea of approach 3 and smart `TermLike` constructors. IMHO one should never have to edit the attributes unless the  underlying `TermLikeF` has changed (in principle, these attributes should be a _cache_ for computable term properties - some aren't, though)

**Comment by treeowl** [comment]
The salting issue is pretty much inherent to hash caching. I believe the whole concept is a no-go if salt is essential to the application.

**Comment by treeowl** [comment]
Maybe that was slightly too strong. In principle, we could cache a wide, cryptographically strong hash, and salt that, but I wouldn't expect that to perform terribly well.

**Comment by treeowl** [comment]
There's a definite tension between caching hashes and the fusion benefits of laziness. For example, the documentation of `fromConcrete` states that

> `fromConcrete` unfolds the resulting syntax tree lazily, so it
composes with other tree transformations without allocating intermediates.

The same is true of `Kore.Internal.TermLike.TermLike.mapVariables`. These functions work lazily from the top down. Hashing, on the other hand, works strictly from the bottom up—nothing can be learned about the hash of the tree until the hashes of its subtrees are known. If we use lazy data structures (as in the current code), computing the hash of a term for the first time will force a tree full of hash thunks. Not terrible, but probably not great for cache utilization. If we use strict ones, then of course we'll lose the cache-beneficial "fusion" effect of laziness. Is there an alternative to hashing for our purpose? How are these hashes used?

**Comment by goodlyrottenapple** [comment]
The sole purpose of hashing is for the use of hash sets/maps for caching. As previously investigated by Serokell, we get good caching, i.e. high cache hits, but at the cost of expensive hash computation at every lookup. We have investigated the use of unordered containers in a more localised part of the code, namely the MultiAnd/MultiOr data structures and believe we found them roughly on par with the hash versions, i.e. the speedup of using hash-maps was roughly cancelled out by to the expensive hashing. I was toying with the idea of perhaps doing some sort of a bounded hash which only recurses a few levels of a term, the idea being that we don't care about the hash being unique as long as collisions don't happen too frequently.

**Comment by treeowl** [comment]
> We have investigated the use of unordered containers in a more localised part of the code, namely the MultiAnd/MultiOr data structures and believe we found them roughly on par with the hash versions, i.e. the speedup of using hash-maps was roughly cancelled out by to the expensive hashing.

I don't understand. `unordered-containers` uses hashing.

**Comment by treeowl** [comment]
> sorry, i meant ordered containers

The alternative container type that comes to mind is the trie. Something like `generic-trie`, maybe. I can't say if that would be better than `HashMap`, but it has a much better chance than `Map`.

**Comment by ana-pantilie** [comment]
Questions:
- TermLike.toConcrete: does this actually rely on laziness?

**Comment by ehildenb** [comment]
Following the discussion today, we concluded that using the Trie data-structure will be optimizing for the cache-miss case (throwing out potential cache hits earlier), _not_ for the cache-hit case. Because our cache-hit ratio is 95% already, it seems unlike to be an optimization, and will mean we're using some non-standard (or less-standard) datastructures.

Seems to me it's better to pursue the incremental hashing approach from here, and try to get that codebase working.

**Comment by ana-pantilie** [comment]
`make clean; make golden` or `make golden -B`, remove kore-rpc directory or other dirs which don't use golden files

**Comment by ana-pantilie** [comment]
`--dry-run` just print out what it would run
`-jn` run `n` processes in parallel
`-B` force rewrite
