### ISSUE TITLE
Overhaul graph traversal/execution strategy

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3143]
- [x] #3168
- [x] Design work towards JSON-RPC new functionality
- [x] Create a front-end ticket when this is done, so we can update the pyk library

**Comment by jberthold** [comment]
## Analysing the JSON-RPC API vs. `execute` requirements

### JSON RPC API data for `execute`
(Description in docs/2022-07-18-JSON-RPC-Server-API.md)

* Request data (exemplified)
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "execute",
  "params": {
    "max-depth": 1,
    "cut-point-rules": ["rule1"],
    "terminal-rules": ["ruleFoo"],
    "state": { <TERM IN KORE JSON FORMAT> }
  }
}
```

* Responses (for successful execution)
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "states": [ LIST_OF_RESULT_STATES ],
    "reason": REASON
  }
}
```
  with   
  * `REASON`:  
    string, one of { `final-state`, `branching`, `stuck`, `depth-bound`, `cut-point-rule`, `terminal-rule`}
  * LIST_OF_RESULT_STATES:  
    a list of objects with `state` (KORE term) and `depth` (depth reached)
    
  Depending on `reason`, the list will contain the following:
  1. (`final-state`) a single term (the final state)
  2. (`branching`) a list of more than one next states
  3. (`stuck`) a single stuck state
  4. (`depth-bound`) a single (non-final, usually non-stuck) state
  5. (`cut-point-rule`) a list of next states (after applying a cut point rule)
  6. (`terminal-rule`) a single final state (after applying a terminal rule)

### Suggestions

#### Stop-on-branching invariant
The data model chosen for the `execute` RPC call requires it to never execute across a branch point. Otherwise, results of an execution would potentially contain combinations of the above `reason`s, which is not supported.

#### Indicating which rule led to stopping
For cases 5 and 6 above, the particular rule that led to stopping should be indicated in an additional field. This could be done by extending making the `reason` field contain an object in these cases, or by adding an optional `rule` field ignored for any reason other than `cut-point-rule` or `terminal-rule`)

#### Possible merger of `reason`s
There is no essential difference between `branching` and `cut-point-rule` other than the suggested `rule` field. Likewise, `final-state` and `terminal-rule` could be merged by determining from the `rule` field which particular case led to termination.

### Implementation of `execute` to support the above requirements

The starting point of the discussion is the current [`GraphTraversal` implementation ](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec/GraphTraversal.hs#L171)
with [helper functions to produce the result interpretation function](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec.hs#L349)

* `max-depth` is supported by way of limiting the "instruction" length provided to the traversal function.
* Execution can be stopped on branch points (but is currently not for `kore-exec`).
* Execution depth is tracked at the call site of `graphTraversal`
(see [`kore-exec`](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec.hs#L282-L301)), which provides support for returning the `depth` reached.
* To support `cut-point` and `terminal` rules, the result interpretation function needs to be extended to
	- stop the traversal with `Final` _after_ a `terminal` rule was used
	- stop the traversal with `Stopped` (providing next states) when a `cut-point` rule was used.

  In both cases, extracting the particular rule that was used requires modifications. This will be best achieved by extending the traversal state with rule information, in a way similar to how execution depth is tracked at the moment.
* While it is possible to derive the reason for stopping the traversal by from the existing traversal result constructors and their data, the alternatives [`Ended`, `GotStuck`, and `Aborted`](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec/GraphTraversal.hs#L148-L164)
are probably not a good description of what exactly they implement.  
To better describe results, the `TraversalResult` type should be extended to distinguish a `Stopped` result (containing possibly several next states) from a `GotStuck` result. `Aborted` should remain reserved for exceptional cases (currently only used when exceeding the breadth limit).

**Comment by jberthold** [comment]
## Amended JSON RPC API data for `execute`
(Description in docs/2022-07-18-JSON-RPC-Server-API.md)

* Request data (exemplified)
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "execute",
  "params": {
    "max-depth": 1,
    "cut-point-rules": ["rule1"],
    "terminal-rules": ["ruleFoo"],
    "state": { <TERM IN KORE JSON FORMAT> }
  }
}
```

* Responses (for successful execution).
 
  **CHANGES:** 
  - added current state field
  - added rule field
  - renamed states to `next-states` (optional now)
  - moved `depth` field outside `next-states`


```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "state": { <TERM IN KORE JSON FORMAT> },
    "depth": 42,
    "reason": REASON,
    "next-states": [ <LIST OF TERMS IN KORE JSON FORMAT> ],
    "rule": "rule1"
  }
}
```
  with the following contents:

  * `reason` contains a 
    string, one of { `branching`, `stuck`, `depth-bound`, `cut-point-rule`, `terminal-rule` }

  * `state` contains the state reached,
  * `depth` indicates the execution depth,
  * `rule` and `next-states` are optional and only relevant when `reason` is `branching`, `cut-point-rule` or `terminal-rule`.
      - When stopping due to a `cut-point-rule` or `terminal-rule` match, rule` contains the rule ID or label. `rule` is empty for ordinary branch points.
      - When a branch point is reached (reason is `branching`), `next-states` contains the list of states reached after the branch;
      - When stopping at a `cut-point-rule`, `state` is the LHS of this cut-point-rule, and `next-states` contains the list of (possibly several) states reached after the cut-point.
      - When stopping at a `terminal-rule` (i.e., `state` is RHS of a terminal rule), and `next-states` is empty.

### Comments

#### Stop-on-branching invariant
The data model chosen for the `execute` RPC call requires it to never execute across a branch point. Otherwise, results of an execution would potentially contain combinations of the above `reason`s, which is not supported.

#### Possible to merge several reasons to a single one
There is no essential difference between ordinary execution branching and stopping due to using a `cut-point-rule`, other than that the cut-point does not always have more than one next state and has the `rule` field filled.
Likewise, reaching a `terminal-rule` can simply return an empty `next-states` list and the rule ID/label.

The contents of the `rule` and `next-states` fields would indicate which particular case led to stopping the execution.

| Reason             | rule filled      | rule empty  |
|------------------- | ---------------- | ----------- |
| next-states filled | `cut-point-rule` | `branching` |
| next-states empty  | `terminal-rule`  |  (other)    |


We could merge reasons `branching`, `cut-point-rule` and `terminal-rule` to a single reason `stopped`, and even include `stuck` and `depth-bound` by using the `(other)` case above and considering the `depth` field.  
However, this would require all clients to implement this same logic, it is easier to indicate the different cases in the `reason` field, too.

### Implementation of `execute` to support the above requirements

The starting point of the discussion is the current [`GraphTraversal` implementation ](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec/GraphTraversal.hs#L171)
with [helper functions to produce the result interpretation function](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec.hs#L349)

* `max-depth` is supported by way of limiting the "instruction" length provided to the traversal function.
* Execution depth is tracked at the call site of `graphTraversal`
(see [`kore-exec`](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec.hs#L282-L301)), which provides support for returning the `depth` reached.
* Execution can be stopped on branch points (but is currently not for `kore-exec`). The _next_ states are returned in that case.  
  To support returning the state before a branch additionally, the `Stopped` transition result needs to be extended with a "current state" field.

* To support `cut-point` and `terminal` rules, the same extension to the `Stopped` result is required. 
 The result interpretation function needs to be adapted to
	- stop the traversal with `Stopped` _after_ a `terminal` rule was used,
	  returning the state reached (RHS) and an empty list of next states;
	- stop the traversal with `Stopped` (providing the LHS, i.e., prior state, and the next states) when a `cut-point` rule was used.

  In both cases, the particular rule that was used must be extracted. This will be best achieved by extending the traversal state with rule information, in a way similar to how execution depth is tracked at the moment.

* Similar to the transition result type, the [`TraversalResult` type](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Exec/GraphTraversal.hs#L148-L164) must be extended to support returning both the last state(s) reached and the possible next states in the result, extending the existing alternatives `Ended`, `GotStuck`, and `Aborted`.

`Ended` and `GotStuck` both carry a list of states reached, but previously, `GotStuck` was also used for cases where the execution depth bound was reached (containing non-stuck states in that case). This should be changed in the existing code for `kore-exec`.  
`Aborted` should remain reserved for exceptional cases (currently only used when exceeding the breadth limit).
