### ISSUE TITLE
Option to adjust the number of solver query retries

### ISSUE THREAD

**Issue by nwatson22** [runtimeverification/haskell-backend#3162]
Currently if a z3 query returns unknown, the haskell backend can rerun it once. We could add a command-line option, something like `--max-solver-retries [number]`, to specify how many times the user is willing to retry these, where on each successive retry the timeout would be doubled. This could give the user more control over the z3 timeout and make it easier to figure out how long an expensive query is taking.

**Comment by ehildenb** [comment]
The default should be `1`, and on that retry the default timeout should be 80ms. But this gives the user an easy way to say "maybe the problem is solver timeouts, let's try and get it passing by just giving the solver more time".

**Comment by jberthold** [comment]
Suggest to not _double_ the timeout but instead only _add_ the default value, to avoid astronomic values when users use a large number.

**Comment by ana-pantilie** [comment]
@JKTKops This is where we retry failed queries: https://github.com/runtimeverification/haskell-backend/blob/fd06257c53e761d93a81a760a03fdd28195ea11d/kore/src/Kore/Rewrite/SMT/Evaluator.hs#L185

**Comment by JKTKops** [comment]
> Suggest to not _double_ the timeout but instead only _add_ the default value, to avoid astronomic values when users use a large number.

I went with (nearly) this plan. I recorded the `TimeOut` setting before starting to do any retries and use multiples of it for each retry. The first retry uses the original timeout (this matches the old behavior^1) then twice it, then 3x, then 4x, etc. A new option `--smt-retry-limit` can be used to configure how many times we will retry.

----------

^1: Previously, we had SMT retries because sometimes `z3` decides existence is pain and it wants to share the message (read: it just gives up). We would retry a query once if `z3` gives up in case this is what happened. No extra timeout is needed for that.

However, correspondingly, we would also re-initialize the solver before the retry. I've left this re-initialization, so it will happen between every retry. I don't think this is very expensive so that should be fine, but if this turns out to be not ideal it should be easy to change.
