### ISSUE TITLE
Revise GitHub runner cache to accelerate partial rebuilds

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3165]
Observation from @jberthold : we are rebuilding all modules all the time, even though we have a build cache.

**Comment by goodlyrottenapple** [comment]
I believe I know what the issue is. Per github docs and confirmed by this [stack overflow answer](https://stackoverflow.com/a/66632107), a cache will only be available to the descendants of the branch int was created on. The problem is, we cache inside feature branches and not in the main branch, so when we open another feature branch unrelated to the original brnach we made the cache in, there is no cache hit, even tho the keys are deterministic and match. The solution is to set up another action triggered on the main branch which checks+updates the cache
