### ISSUE TITLE
Simple symbolic execution with definedness checking turned off

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3175]
This proof suite used for profiling: https://drive.google.com/drive/folders/1MxmKtx6sHkkGQPlruptj5vAwr4JfV6Uc?usp=sharing

Is a bunch of really short KEVM executions, that I suspect do not need definedness checking turned on at all past the original check for the LHS of the proof. I think the only rule they should be exercising that has any potentially undefined symbols on the RHS is this one:

```
    rule [step]: <k> (. => #next [ #dasmOpCode(PGM [ PCOUNT ], SCHED) ]) ~> #execute ... </k> 
                 <pc> PCOUNT </pc> 
                 <program> PGM </program> 
                 <schedule> SCHED </schedule> 
      requires PCOUNT <Int #sizeByteArray(PGM) 
```

Where it does the lookup `PGM [ PCOUNT ]` (`PCOUNT` may not be in the indices of `PGM`, which is a `Bytes` (byte-array)).

But in the case of _these_ executions, `PCOUNT ==Int 0` for the entirety of the execution, and `len(PGM) > 0`, so it will be defined.

So the question is: if we only do the definedness check at the beginning of execution, and otherwise completely disable definedness checking (which should be safe for these executions), do we notice a performance difference? Note that we should probably still do the initial definedness check on the definition (which checks that the proof LHS is well-defined), but not any during execution.

If this ends up improving performance during the execution phase of these tests, then it's worth investigating a new tool that analyzes the definition ahead of time and annotates rules with `preserves-definedness` if they are guaranteed to preserve definedness (do this analysis on all rules in the definition). This analysis can be done by computing `#Ceil(LHS) #Implies #Ceil(RHS)` I believe (checking that it's `#Top`), but someone should confirm. Then, only when we apply some rule that does _not_ have this attribute, do we need to actually check definedness.

**Comment by ehildenb** [comment]
In fact, we may be able to just statically compute, for each rule, the minimal definedness check it needs to do. Maybe we can just compute `#Ceil(RHS)` for each rule in the semantics, and attempt to simplify it ahead of time. For many rules, which have purely functional or constructor RHS, it can probably statically simplify out to `#Top`. For rules with potentially undefined portions, we'll get a minimized definedness check for just those potentially undefined portions.

**Comment by ana-pantilie** [comment]
One thing we need to understand properly before designing this feature is why KEVM needs #ceil simplification rules and what impact that has on this issue.

**Comment by ana-pantilie** [comment]
I want to post-pone this issue until we fix the way we do ceil simplification. After https://github.com/runtimeverification/haskell-backend/issues/3126 is done, we should re-evaluate the situation and see if a solution like this is necessary.

**Comment by ehildenb** [comment]
Ok, what is the progress of ceil simplification fix?

**Comment by ana-pantilie** [comment]
It's WIP. The reason I'm focusing on that is that ceil simplification _should not_ take that long. The fact that it does is a bug, so I believe it to be avoidable.

**Comment by ehildenb** [comment]
Well that's fine, but if it's a WIP for 6 weeks, and we could have had some improvement with 2 days of work, then we should do the 2 day fix. We cannot block immediate progress on potential future progress, that is falling into the trap of "the perfect is the enemy of the good". https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good

Getting a faster backend 6 weeks earlier because we did something less tasteful (but still sound) _now_ means 6 weeks of innovation that can happen downstream while you work out a better solution.

**Comment by ana-pantilie** [comment]
Sure, that's definitely true, I just didn't think this is a 2 day task. "Disabling definedness checking" is not that simple. I think something like this has some design considerations which take more time than we can allocate for quick experiments.

Some questions that need to be answered:
- Each step we assume that the configuration is defined. Would having a "preserves definedness" attribute be more useful than what we currently do? Note that we make that assumption so that the simplifier can simplify more terms (and send more information to the SMT).
- Where do we call the ceil simplifier and why?
- If we know that a semantic rule preserves definedness, which calls can we remove? Which calls can't we? Why? Is there any more information that we could get statically which would help us decide if we need those calls or not?
- We already cache a lot of information about definedness, so that it doesn't need to be recomputed. Why isn't this enough?

And with that last bullet point we enter the "why is ceil simplification so slow right now?" territory which I'm trying to understand and fix. 😄 

I think I get where you're coming from, that definedness checking isn't really an integral part of symbolic execution. But simplification in ML depends so much on it, so we have definedness checks ingrained into the logic and assumptions of the backend in many places. It doesn't seem obvious to me how to quickly separate definedness from the rest.
