### ISSUE TITLE
JSON-RPC: implement check-implication

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3208]

**Comment by jberthold** [comment]
There is existing code in the prover, see https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Reachability/Claim.hs#L567-L571 
(also see the [description of the algorithm](https://github.com/runtimeverification/haskell-backend/blob/master/docs/2020-06-17-Checking-Implication.md))
What prevents us from reusing it is that this algorithm is focused on _checking_ the implication (by way of refuting the negation), rather than computing a simpler version or a substitution witnessing it, which we want to return to the RPC client.
A first [new version has been implemented in #3212](https://github.com/runtimeverification/haskell-backend/pull/3212/files#diff-e9fa99df1a36c20b42caa09ea6fb4ddfc7b6b3fc2485df4da2c8403fbe506f0bR665-R714) but should be optimised further to align with the modified goals.

**Comment by jberthold** [comment]
Sketch of an alternative procedure, by @ehildenb :

> Given two constrained term patterns `CT1` and `CT2`, we can first compute and simplify `CT1 #Implies CT2` as much as possible [before trying to prove or disprove something].
> Let `CT1 == T1 /\ C1` , and `CT2 == T2 /\ C2`. We first compute T1 #Implies T2 to get a substitution alpha
> Then we apply alpha to `T2 /\ C2`, and then compute `C1 #Implies alpha(C2)`
> This can, in [..][many] cases, be directly syntactically simplified to `#Top` , or to some much smaller core problem `C1' #Implies C2'`
> Which can then be fed into the original implication procedure [and returned to the user if the implication cannot be shown to be true].

**Comment by jberthold** [comment]
From stand-up discussion:
* When stuck, we should return the simplified implication (paraphrased `\implies (LHS, \exists(existentials, RHS))`) (possibly even in all cases, as the unifier we return relates to this simplified implication)
* A few of the unit tests are obsolete because we now simplify the input patterns before trying to check the implication.
