### ISSUE TITLE
Long KEVM proof

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3216]
This is a simple Solidity program:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity =0.8.13;
                 
import "forge-std/Test.sol";

contract Token{  

}
                 
contract DealTest is Test {

    function testDeal(uint256 value) public {
        Token alice = new Token();
        vm.deal(address(alice), value);
        assertEq(address(alice).balance, value);
    }             
}
```

I am generating a KEVM proof from it, and running said proof. It takes too long (8m52s s on my machine). I want it to take 20s.

Attached is the bug report.

[foundry.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9405196/foundry.tar.gz)

**Comment by ehildenb** [comment]
Do we have a standard testing harness that can run these bug reports through the profiler? If not, what are the default first profiling steps we should do with these bug reports? Let's write the instructions down, and then we can figure out a way to automatically collect that profiling information and attach it to the issue here.

@ana-pantilie @jberthold and @goodlyrottenapple , when you get a "profile this and make it faster" request, what are the first things that should be attempted?

**Comment by ana-pantilie** [comment]
> Do we have a standard testing harness that can run these bug reports through the profiler?
Not really, you just need to configure cabal to build the backend with profiling, and then run the test with some RTS options which will output profiling info. For time profiling, the steps are described here: https://github.com/runtimeverification/haskell-backend/wiki/Profiling#haskell-profiling.

I usually do eventlog profiling, as described in the link above. One thing to mention here, is that you need to tweak the timeout, since Speedscope can't handle eventlog files which are too large. I've noticed that between 3 min and 5 min I usually get good results.

> we can figure out a way to automatically collect that profiling information and attach it to the issue here
When opening an issue, if you could also attach one of these Speedscope profiles that would be useful. We could quickly look at the profile and assess if it is a known problem or not.

There's also https://github.com/runtimeverification/haskell-backend/blob/master/docs/profiling.md which was recently added by @goodlyrottenapple . That also documents memory profiling options. That kind of profiling is useful when the test ends with the warning regarding productivity, or if you notice your test is using up more and more memory over time. I'm not sure how useful automating this would be, though, I haven't done memory profiling in a while and I haven't tried the newer options on the GHC 9 build, so maybe @goodlyrottenapple or @jberthold have a more up-to-date perspective on this.

**Comment by ehildenb** [comment]
Issue made: https://github.com/runtimeverification/haskell-backend/issues/3221

**Comment by ana-pantilie** [comment]
Thanks @ehildenb !

**Comment by ana-pantilie** [comment]
We should just profile and report what we find.

**Comment by ehildenb** [comment]
Yes, this can be used as an exercise to inform the steps we want to use for #3221 .

**Comment by ehildenb** [comment]
Running new profiles should be very simple, ideally the build system would have a direct way to consume the tarball and produce the profiles.

**Comment by ehildenb** [comment]
@ana-pantilie any progress on this? Did we run the profile manually yet?

**Comment by ana-pantilie** [comment]
@ehildenb https://github.com/runtimeverification/haskell-backend/issues/3221 should be done soon. When it is, I'll re-open this issue using the template from https://github.com/runtimeverification/haskell-backend/pull/3265. The team will meet and we'll look over the data together.

I did take a look at one of the profiles by myself, and I believe that we already have WIP or planned work to improve the hotspots present in the profile. If we find anything new we'll open new issues and link this one to them.

**Comment by jberthold** [comment]
I am triggering a new test run by writing text that contains the sequence `.tar.gz`

**Comment by jberthold** [comment]
The profiling run above (using latest master with new ceil simplifier) produced no immediate new clues. The (non-profiled) run was cut short after 4 minutes, profiling shows `hashWithSalt` and `liftSimplifier` (as well as `ravel` from the generic lenses) to be big consumers.
On my machine (12th gen. i9 with 16 + 8 cores) the proof finishes after 3 minutes now, though.
