### ISSUE TITLE
Some symbols from the K standard library are just symbols, not hooked one

### ISSUE THREAD

**Issue by amelieled** [runtimeverification/haskell-backend#3253]
Hi everyone!

After running `kompile imp-lib.k` (See [imp-lib.zip](https://github.com/runtimeverification/haskell-backend/files/9556777/imp-lib.zip)), the symbols `freshInt` and `dividesInt` are generated from the K standard library, but there aren't `hooked-symbol` (just `symbol`).

**Comment by dwightguth** [comment]
This is also not a bug. Neither of these functions are hooks.

**Comment by amelieled** [comment]
Why these symbols aren't?

For my understanding, the K standard library is an interface that each backend needs to implement.
There are just syntax sugar?

**Comment by ana-pantilie** [comment]
@amelieled `freshInt` is defined in [domains.md](https://github.com/runtimeverification/k/blob/master/k-distribution/include/kframework/builtin/domains.md#implementation-of-integers). So it's a regular function symbol, with the implementation given by the rule beneath it.

I'm not sure why you think this should be hooked.

By the way, https://github.com/runtimeverification/k is the right repository for reporting bugs regarding the way the Kore definition is generated. Since the Kore language is very stable, there's a small chance of finding such bugs. It would be best to ask on our [K Slack channel](https://runtimeverification.slack.com/archives/C7E701MFG). Let me know (in a DM on Slack) if you don't have access to it.

**Comment by amelieled** [comment]
Thanks @ana-pantilie .
I don't understand something about hooked thing, so I will ask on the K Slack channel.
(Another example: `SortBool` is hooked, but not `SortId`.)
