### ISSUE TITLE
Execute endpoint of `kore-rpc` does not perform rewriting

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/haskell-backend#3283]
When running the `execute` endpoint of `kore-rpc` over a simple `imp` definition, the server fails to rewrite the configuration (i.e. respons with reason `stuck` and depth `0`). When using the same configuration as the LHS of a claim, `kprove` does the rewriting as expected.

## Resources

```
K version:    v5.4.7-0-g0b0189cc60
Build date:   Tue Sep 27 13:19:45 CEST 2022
```

Files for reproducing the issue: [kore-rpc-debug.zip](https://github.com/runtimeverification/haskell-backend/files/9665742/kore-rpc-debug.zip)

```
kore-rpc-debug
├── imp.k
├── imp-verification.k
├── report.tar.gz
├── request.json
├── request.kast
├── request.kore
├── request.pretty
├── response.json
├── response.kast
├── response.kore
├── response.pretty
└── spec.k
``` 

## Steps for reproducing the issue

First, we kompile the definition.

```
% kompile imp-verification.k --backend haskell
```

Then start `kore-rpc`.

```bash
% kore-rpc imp-verification-kompiled/definition.kore --module IMP-VERIFICATION --server-port 3000
```

Then we can call the endpoint.

```bash
% netcat -q 0 localhost 3000 < request.json > response.json
```

Here, `request.json` (also `request.kore` and `request.kast`) is derived from `request.pretty`.

```k
<T>
  <k> int $n ; $n = 0 ; </k>
  <state> .Map </state>
</T>
```

Similarly, from `response.json` we can derive `response.pretty` (also `response.kore` and `response.kast`) .

```k
<T>
  <k>
    int $n, .Ids;
    $n = 0; ~> .
  </k>
  <state>
    .Map
  </state>
</T> ~> .
```

It can be seen that no rewriting has been performed on the input.

## Expected result

To demonstrate that rewriting should have been performed, we can write a simple specification `spec.k` with a single claim.

```k
requires "imp-verification.k"

module SPEC
    imports IMP-VERIFICATION

    claim <T>
            <k> int $n ; $n = 1 ; => . </k>
            <state> .Map => $n |-> 0 </state>
          </T>
endmodule
```

When running `kprove` over this specification, the tool returns the expected result.

```
% kprove spec.k
kore-exec: [264581] Warning (WarnStuckClaimState):
    The configuration's term doesn't unify with the destination's term and the configuration cannot be rewritten further. Location: /home/ttoth/git/kore-rpc-debug/spec.k:6:11-9:15
Context:
    (InfoReachability) while checking the implication
<T>
  <k>
    .
  </k>
  <state>
    $n |-> 1
  </state>
</T>
[Error] Prover: backend terminated because the configuration cannot be
rewritten further. See output for more details.
```

This step can be reproduced based on `report.tar.gz` as well.

**Comment by jberthold** [comment]
Thanks for the detailed description, this made it much easier to debug what was going on.

There were two problems in the `request.json` input:
* It had a stray `~> .k` outside the `T` cell;
* The `generatedTop` and `generatedCounter` cell are missing. These two cells are always present and surround the user-defined or automatic configuration.

The actual state encoded in `request.json` looks approximately like this: (pseudo-K config syntax, injections as commments)

```
 <T> <!-- injection: TCell -> KItem -->
  <k>
    <!-- injection: Pgm -> KItem -->
    int $n;
    $n = 0; <!-- injection: Int -> AExp -->
   ~>
    .k
  </k>
 <state>
  .Map
 </state>
 </T>
~>
 .k
```
Instead, it should look more like this: (injections omitted) for the request to be actually executed:
```
<generatedTop>
 <T>
  <k>
      int $n; 
      $n = 1;
    ~> 
    .k
  </k>
  <state>
    .Map
  </state>
 </T>
 <generatedCounter>
  0
 </generatedCounter>
</generatedTop>
```
I have [modified the `request.json` so it represents this configuration (request-with-top-cell.json.txt)](https://github.com/runtimeverification/haskell-backend/files/9671276/request-with-top-cell.json.txt), and it is executed to a depth of 3.
It is still getting `stuck` because there is obviously no way to rewrite the final state, but it returns the expected final state with no instructions left.

One could argue we should simply add the `generatedTop` and `generatedCounter` to execute requests automatically. However, the response will always contain those and we would need to strip them from the response to stay consistent (e.g., enable feeding the output state back into the next request). I would rather not introduce such magic.
