### ISSUE TITLE
Remove UnifierT

### ISSUE THREAD

**Issue by treeowl** [runtimeverification/haskell-backend#3422]
Currently, we have both `NewUnifier` and the older `UnifierT`. `NewUnifier` should be more efficient, so we should endeavor to use it exclusively.

**Comment by treeowl** [comment]
I know I'm supposed to set a project, but it only offers me three of those, none of which look familiar.

**Comment by goodlyrottenapple** [comment]
I have been looking at the old vs new unifier recently and one question I had about the new unifier vs the old was the treatment of other non-free bits of the theory, e.g. `⊤`. Usually, a unification procedure carries the following invariant:
```
∀t1 t2. let σ = unify t1 t2 in 
   σ ≠ ⊥ ⇒ σ t1 ≡ σ t2
```
where `≡`  is syntactic/structural equality in a free theory and modulo equations in non-free theory. 
However, as far as I can tell from the code, the unification of `⊤` with any term `t` in the new unifier will succeed, producing an empty substitution:

https://github.com/runtimeverification/haskell-backend/blob/4e9bd015e26f958160f2998a480b3faf00bb8950/kore/src/Kore/Unification/NewUnifier.hs#L425-L426

Thus, AFAICS the above condition does not hold in this example for the usual structural equality modulo AC equations. __Is this something that can occur in practice? Should this even unify, given the above assumption about unification, or is the assumption not quite right, given the setting of matching logic?__

The above IMO illustrates the trickiness of trying to replace the old unifier with the new one, since the old unifier is a unifier mixed in with an `∧` simplifier. This is due to the `∧` being used to both encode unification as `t1 ∧ t2` as well as being a matching logic connective which has simplification rules such as `⊤ ∧ t ≡ t`. In concrete terms, it seems to me that if we want to replace the old unifier+simplifier with the new unifier and achieve parity, we would have to disentangle the simplifications of `∧` from the unification bit in the old code path first, to understand what extra reasoning the old unifier+simplifier does that the new unifier does not/cannot do.

I believe the above task would be a multi month effort on its own...

**Comment by treeowl** [comment]
I went through all the evm tests. The only one that fails is test-storagevar03.sh. I've attached the error.
[storagevar03-output.txt](https://github.com/runtimeverification/haskell-backend/files/10464456/storagevar03-output.txt)

**Comment by ehildenb** [comment]
One way to test if this is used in practice is to just replace the RHS of those two cases with errors, and see if the errors are triggered when running all the test-suites we know about.
