### ISSUE TITLE
Automate regression test updates using Github Actions

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3577]
- we'd like to be able to run the job at the click of a button
- would also be good to run it on a schedule
- the job should run the `scripts/generate-regression-tests.sh` (recently updated in https://github.com/runtimeverification/haskell-backend/pull/3576)
- for now, focus on KEVM

**Comment by jberthold** [comment]
The script from #3576 is borken because of [changes porting the Makefile logic to pyk which removed the targets for single tests](https://github.com/runtimeverification/evm-semantics/commit/2dc77d846257fe1cdfb28b497c99418b46379e51#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52)... fixing
