### ISSUE TITLE
Variable substitution makes symbolic execution OX

### ISSUE THREAD

**Issue by PetarMax** [runtimeverification/haskell-backend#3648]
I have observed that if we learn during execution that two symbolic variables are equal, the symbolic engine may perform a substitution of one variable for another but not add the equality to the path constraint. This makes the symbolic execution inherently over-approximating, in the sense that it is no longer the case that the path constraint of the next states implies the path constraint of the initial state. 

I am not sure that this behaviour is desired.

**Comment by geo2a** [comment]
@PetarMax I've developed a simple [integration test](https://github.com/runtimeverification/hs-backend-booster/pull/291) that demonstrates that `kore-rpc-dev` (this is testing version of `kore-rpc` equivalent to `kore-rpc` itself of all intents and purposes) in fact does:
* learn that `X #Equals Y` from an ensures clause
* substitute `X` for `Y in the configuration
* return `X #Equals Y` in `substitution`

Now, `kore-rpc-booster` has a slightly different behavior (and we will talk internally about what to do with it), but as I understand you are concerned with `kore-rpc`.

In `pyk`, the result of the `execute`, which has three components (`term`, `substitution` and `predicate`) is pasted together as `#And`: https://github.com/runtimeverification/pyk/blob/a18d76df9419194acf1f9d159d8fa697e0471bd9/src/pyk/kore/rpc.py#L365 --- this behavior should retain the substitution. So the reason is indeed likely in `kore-rpc`.

Could you steer me towards a larger example that would exhibit the over-approximating behavior?

**Comment by PetarMax** [comment]
Apologies, I seem to have missed something in my larger example, since it had numerous constraints - it does have the equality.
