### ISSUE TITLE
Regression in `pyk` integration tests

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/haskell-backend#3662]
Analysis: https://github.com/runtimeverification/pyk/pull/649#issuecomment-1729574664

**Comment by geo2a** [comment]
The problem was in the fact we've returned a `"branching"` result with only one branch, which `pyk` interpreted as `"stuck"`.  

It turns out, Sam ahs already made a subsequent patch (https://github.com/runtimeverification/haskell-backend/pull/3653) to HB, and I've completely forgotten about it. I've approved the dependency update to K (https://github.com/runtimeverification/k/pull/3633) which would merge it. Once this change propagates here, the test will be green again.

I've verified locally by doing:
```
kup install k --version 06734ea77b9ed0037619d81cf193cb1198701f2a
cd pyk
make test-integration TEST_ARGS='-k imp-simple-sum-loop'
```

@tothtamas28 we can keep this open until the update propagates from K to `pyk`.
