### ISSUE TITLE
Backend gets stuck applying `#Ceil` rule for Maps

### ISSUE THREAD

**Issue by lucasmt** [runtimeverification/haskell-backend#3703]
The proof I'm running gets stuck in an execute request deep in the execution, with no progress made after at least 10 hours. The bug report has been shared on Slack. According to @jberthold,

> FWIW the loop occurs after 2593 steps. I have extracted the state at that point (attached). If you send that state in an execute request (rpc-client execute state-at-2593.json) it will
> * immediately abort in booster (after 0 steps)
> * fall back to kore, which will get trapped in a simplification loop

> The rules that get repeatedly applied are
> ```
> definition.kore:146565:24
> domains.md:452:8-452:165
> ```

> (the domains.md rule up to 3 times before the other one fires again, in my observations)

The rule in `definition.kore` is a `#Ceil` rule, and the one in `domains.md` relates to `in_keys`. They don't seem to be caught in a loop, but they are repeatedly applied, maybe because of the size and number of maps in the configuration. The maps are mostly concrete, but have a few entries with a symbolic variable.

**Comment by geo2a** [comment]
Unfortunately have to reopen this. I was under the impression that it was fixed by https://github.com/runtimeverification/haskell-backend/pull/3705, but this is not true.

With the current `kore-rpc-booster`, we make a little more progress (probably because we apply more rules in Booster), and get stuck at depth 2807 now. The symptoms are the same: we get stuck in Kore's simplifier and the same rules as above turn-up, with an addition of a number of others.
