### ISSUE TITLE
Booster aborts when simplification side condition can't be evaluated

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/haskell-backend#3804]
The booster backend does not seem to be able to evaluate g in the definition below. I would argue that if it's not able to evaluate f(I) <Int 0, then it should use the second simplification rule, as the Haskell backend does.
```
module TEST
  imports BOOL
  imports BYTES
  imports INT

  syntax A ::= a(Int) | "b"
  rule a(I) => b requires g(I)

  syntax Int ::= f(Int)  [function, total, no-evaluators]
 
  syntax Bool ::= g(Int)  [function]

  rule g(I) => true requires f(I) <Int 0 [simplification(50)]
  rule g(_) => true [simplification(51)]

endmodule
```

If I run this claim, then the booster falls back to the Haskell backend:

```
module TEST-SPEC
  imports TEST

  claim <k> a(I) => b ... </k>
endmodule
```

**Comment by geo2a** [comment]
Compiling:
```
kompile --backend haskell test.k --emit-json 
```
and proving the spec:
```
pyk prove test-spec.k --verbose --kore-rpc-command 'kore-rpc-booster -l Simplify'
```
reveals that Booster cannot simplify `g` because the simplification rule in line 14 does not preserve definedness:
```
...
[Simplify] Simplifying term
g(_)_TEST_Bool_Int(VarI:SortInt{})
failed because the rule at
/home/geo2a/org/data/3b/d0c9ce-9843-4466-a86d-cdcee22f7f5d/test.k :  (14, 8) -
does not preserve definedness @(hs-backend-booster-0.0.0-7JDKDPPzRWU6SD0fVFFFCm:Booster.Pattern.ApplyEquations library/Booster/Pattern/ApplyEquations.hs:789:5)
...
```

Marking `g` as total solves the problem. Alternatively, the simplification on line 14 could be marked with `preserves-definedness`.

We could achieve the desired behavior for without marking `g` as total once we have a less conservative definedness story in Booster (see https://github.com/runtimeverification/haskell-backend/issues/3780).

**Comment by virgil-serbanuta** [comment]
Ah, sorry, I think that in my semantics g is actually total, I'll try again to extract a small example.

**Comment by virgil-serbanuta** [comment]
Closing since this is not what the actual bug was.
