### ISSUE TITLE
How to determine from logs why higher-priority rule isn't being applied

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3909]
I'm attaching a bug report, where I'm expecting a higher-priority rule (injected via `add-module`) to be applied as the next step (the bug report is one step long), but instead it applies a rule from the original semantics.

[step.tar.gz](https://github.com/runtimeverification/haskell-backend/files/15500571/step.tar.gz)

In particular, I am working on a modified version of this claim: https://github.com/runtimeverification/evm-semantics/blob/33c69c5421d5ca594a994b9ad946e07eae839db9/tests/specs/mcd/vat-frob-diff-zero-dart-pass-rough-spec.k#L7, and the higher-priority rule is a modified (discharged) version of this claim of an arithmetic function: https://github.com/runtimeverification/evm-semantics/blob/33c69c5421d5ca594a994b9ad946e07eae839db9/tests/specs/mcd/vat-addui-pass-spec.k#L7.

I am trying to debug why it's not applying this rule, and can't get the logs to give me anything useful. So I'm wondering what logging options I'm missing. So far, I've tried `--log-file log --log-context "rewrite*"`, hoping to pick up successful/unsuccessful rewrites in the booster. But it's only giving me log events that are `[kore][simplification]`, but no log events about `execution` or `rewrite`. So I'm wondering if the log events are just not being produced?

**Comment by PetarMax** [comment]
If the request is just for a single step, then I think that full logging with `--log-context "*booster*" --log-context "*kore*"` should show everything, thereby revealing also the options you're looking for?

**Comment by goodlyrottenapple** [comment]
The syntax for the context filtering has changed somewhat. @PetarMax's suggestion is broadly correct, just wanted to mention (in case it catches people out) that the filtering now uses a css like syntax for specifying children/nested contexts. So if one wants a nested context `foo`, this will be captured by `--log-context "*>foo"` or just `--log-context "foo"` if it is a top level context. 

The above `--log-context "*booster*"` will work because `[booster]` is a top level context, but `--log-context "rewrite*"` would only match a log message of the from `[rewrite af122s3] bla`, but not `[booster][execute][rewrite af122s3] bla`. In order to include the latter, we need  `--log-context "*>rewrite*"` or  `--log-context "booster>rewrite*"`

**Comment by ehildenb** [comment]
Where can I find documentation on this new syntax?

**Comment by goodlyrottenapple** [comment]
https://github.com/runtimeverification/haskell-backend/blob/master/docs/logging.md#context-filtering

**Comment by jberthold** [comment]
## To answer the actual question:

I quickly ran the requests manually using `kore-rpc-client` against a server started with `--log-context "booster>execute"` (i.e., context starts with `booster` and contains `execute` somewhere below. I could have used `booster,execute` instead, meaning `booster` immediately followed by `execute`)

To prepare this run, one has to unpack the tarball and then compile the LLVM backend library from the `llvm_definition/definition.kore` file, linking with the blockchain crypto plugin. This is omitted here.

* Starting a server with context logging, output into a file:

```shell
$  ../../.build/kore/bin/kore-rpc-booster ./definition.kore --module VERIFICATION --llvm-backend-library ./interpreter.so --log-context "booster>execute" > step-server-booster-gt-execute.log 2>&1 &
$
```

* Running the `add-module` requests `001` and `002`, and then request `003`:

```shell
$  kore-rpc-client \
      send rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/001_request.json --expect rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/001_response.json \
      send rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_request.json --expect rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_response.json
[Info] Preparing request data
[Info] Sending request rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/001_request.json...
[Info] Response received.
[Info] Round trip time for request 'rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/001_request.json' was 637.992456 ms
[Info] Output matches rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/001_response.json
[Info] Preparing request data
[Info] Sending request rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_request.json...
[Info] Response received.
[Info] Round trip time for request 'rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_request.json' was 741.513257 ms
[Info] Output matches rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_response.json
$
$  kore-rpc-client send rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/003_request.json -o 003-out.json
[Info] Preparing request data
[Info] Sending request rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/003_request.json...
[Info] Response received.
[Info] Round trip time for request 'rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/003_request.json' was 986.903896 ms
[Info] Writing file 003-out.json for the first time.
```

* Terminating the server (`SIGINT` via `^C`)

```shell
$ fg
../../.build/kore/bin/kore-rpc-booster ./definition.kore --module VERIFICATION --llvm-backend-library ./interpreter.so --log-context "booster>execute" > step-server-booster-gt-execute.log 2>&1
^C $
```

* Checking what happened in the log (and inspecting the added module)

```shell
$  tail step-server-booster-gt-execute.log
$  jj -p < rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/001_request.json | less
$  jj -p < rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_request.json | less
$  jj -p params.module < rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_request.json | less
$  jj -p params.module < rpc_VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough/002_request.json > module-002.k
$  emacs module-002.k step-server-booster-gt-execute.log &
```

The module contains a single axiom with label `BASIC-BLOCK-1-TO-2` but no `UNIQUE-ID`, so the context log will have `UNKNOWN` for this rule.

In the log, we first find the hash of the term that is being rewritten (`kore-term` line):

```
[Info] Process request 3 execute
[Info#proxy] Starting execute request
[booster][execute][smt] Starting new SMT solver
[booster][execute][smt] Solver ready to use
[booster][execute][smt] Checking definition prelude
[booster][execute][term 88d06b3][kore-term] <generatedTop>(<kevm>(<k>(#execute_...(one very long line, omitted here)
```
Then the rule `BASIC-BLOCK-1-TO-2` is tried first (its `UNIQUE-ID` is `UNKNOWN`).

```
[booster][execute][term 88d06b3][rewrite UNKNOWN][detail] BASIC-BLOCK-1-TO-2
[booster][execute][term 88d06b3][rewrite UNKNOWN][match][failure] Symbols differ: .WordStack_EVM-TYPES_WordStack() _:__EVM-TYPES_WordStack_Int_WordStack(chop(_)_WORD_Int_Int(VarABI_wad:SortInt{}), _:__EVM-TYPES_WordStack_Int_WordStack(#lookup(_,_)_EVM-TYPES_Int_Map_Int(VarACCT_ID_STORAGE:SortMap{}, keccak(_)_SERIALIZATION_Int_Bytes(_+Bytes__BYTES-HOOKED_Bytes_Bytes_Bytes(#buf(_,_)_BUF-SYNTAX_Bytes_Int_Int("32", VarABI_usr:SortInt{}), #buf(_,_)_BUF-SYNTAX_Bytes_Int_Int("32", keccak(_)_SERIALIZATION_Int_Bytes(_+Bytes__BYTES-HOOKED_Bytes_Bytes_Bytes(#buf(_,_)_BUF-SYNTAX_Bytes_Int_Int("32", VarABI_ilk:SortInt{}), "\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL...truncated")))))), _:__EVM-TYPES_WordStack_Int_WordStack("8766", _:__EVM-TYPES_WordStack_Int_WordStack(chop(_)_WORD_Int_Int(VarABI_wad:SortInt{}), _:__EVM-TYPES_WordStack_Int_WordStack(VarABI_usr:SortInt{}, _:__EVM-TYPES_WordStack_Int_WordStack(VarABI_ilk:SortInt{}, _:__EVM-TYPES_WordStack_Int_WordStack("1704", _:__EVM-TYPES_WordStack_Int_WordStack("2094874590", .WordStack_EVM-TYPES_WordStack()))))))))
```

The rule failed because of a mismatch in the `word-stack` field, which was expected empty `.WordStack...` but contained a cons `_:_...`.

By inspection of the module (a bit cumbersome because it is unformatted and all names are quote-escaped), we find that the generated rule _reqires an empty `<word-stack>`:
`..., Lbl'-LT-'wordStack'-GT-'{}(Lbl'Stop'WordStack'Unds'EVM-TYPES'Unds'WordStack{}()), Lbl'-LT-'localMem'-GT-'{}(...`

The next group of rules by priority is tried.

```
[booster][execute][term 88d06b3][rewrite 1eb6b53][detail] EVM.step
[booster][execute][term 88d06b3][rewrite 1eb6b53][match][success] rewrite 1eb6b53
[booster][execute][term 88d06b3][rewrite 1eb6b53][match][success][substitution] Substitution: Rule#Var_Gen21:SortBlockCell{} -> <block>(<previousHash>(VarPREVIOUSHASH_CELL_2b4a2c...(one very long line, omitted here)
[booster][execute][term 88d06b3][rewrite 1eb6b53][success][term 16fdcb6][kore-term] <generatedTop>(<kevm>(<k>(#next[_]_...(resulting term in one line, omitted)
```

Rule `EVM.step` (unique ID `1eb6v53...`) succeeds. The substitution is printed after the match; no requires clauses are present so the resulting term immediately follows.

More rules (at the same priority level) are tried:

```
[booster][execute][term 88d06b3][rewrite 0752843][detail] EVM.Ccall2-cool
[booster][execute][term 88d06b3][rewrite 0752843][match][failure] Cannot match variable in subject:
VarCONTINUATION:SortK{}
kseq(#freezerCcall(_,_,_,_,_,_)_EVM_Exp_Schedule_BExp_Gas_Gas_Int_Bool1_(kseq(Rule#VarK0:SortSchedule{}, dotk()), kseq(Rule#VarK2:SortGas{}, dotk()), kseq(Rule#VarK3:SortGas{}, dotk()), kseq(Rule#VarK4:SortInt{}, dotk()), kseq(Rule#VarK5:SortBool{}, dotk())), Rule#Var_DotVar2:SortK{})
[booster][execute][term 88d06b3][rewrite 2d5c3f2][detail] EVM.Ccallgas2-cool
[booster][execute][term 88d06b3][rewrite 2d5c3f2][match][failure] Cannot match variable in subject:
VarCONTINUATION:SortK{}
kseq(#freezerCcallgas(_,_,_,_,_,_)_EVM_Exp_Schedule_BExp_Gas_Gas_Int_Bool1_(kseq(Rule#VarK0:SortSchedule{}, dotk()), kseq(Rule#VarK2:SortGas{}, dotk()), kseq(Rule#VarK3:SortGas{}, dotk()), kseq(Rule#VarK4:SortInt{}, dotk()), kseq(Rule#VarK5:SortBool{}, dotk())), Rule#Var_DotVar2:SortK{})
```

These two rules fail because `VarCONTINUATION` occurs in the subject's `k` cell but the rules expect more `kseq` nodes there.[1]
More log lines with failed rule applications follow, each with context `[booster][execute][term 88d06b3][rewrite SOME-UNIQUE-ID]...`. Then, since the request had `max-depth: 1`, the `execute` is finished and the term is simplified (many lines with context `[booster][execute][simplify]...`).

[1] The logging here should actually emit single lines but does not,
this has to be fixed.

**Comment by ehildenb** [comment]
Thanks @jberthold ! I was able to determine that our mechanism for injecting sub-proofs for KClaim style proofs was not working in pyk because of this. Once the rules are appropriately injected, we are indeed getting the needed rules being applied. I think this can be closed!
