### ISSUE TITLE
Missing hook KRYPTO.bn128valid

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#820]

**Comment by ttuegel** [comment]
This is blocking:
- `AND-summary-0-spec`
- `EVMOR-summary-0-spec`
- `NOT-summary-0-spec`
- `XOR-summary-0-spec`

**Comment by ttuegel** [comment]
In the [Java backend](https://github.com/kframework/k/blob/91a69ed56a92897677d16bbdb2065841a4446125/java-backend/src/main/java/org/kframework/backend/java/builtins/BuiltinCryptoOperations.java#L164).

**Comment by ttuegel** [comment]
We should look at the [elliptic-curve](https://github.com/adjoint-io/elliptic-curve) library, which should give us the implementation for "free" as long as we get the correct [parameters](https://github.com/kframework/k/tree/605c1e56f831ed76c98398e9fe544bfbab06c326/java-backend/src/main/java/org/kframework/backend/java/builtins/crypto) from the Java backend.

**Comment by ttuegel** [comment]
We should not need to implement these hooks at this time; it is enough to leave these functions unevaluated. Most likely the hooked functions occur in a branch that should be pruned.

See also: https://runtimeverification.slack.com/archives/CDDCNDUMC/p1564515075132300

**Comment by ttuegel** [comment]
- [ ] Warn if a hook is missing...
- [ ] ...iff there are no axioms provided for the symbol, but
- [ ] ...iff there are axioms provided for any symbol, and
- [ ] ...only warn once.

**Comment by gtrepta** [comment]
@ttuegel The test `tests/iele/danse/unit/precompiled.iele.json.test` in `iele-semantics` is failing on the Haskell backend because this hook is missing.

**Comment by ttuegel** [comment]
@gtrepta Are you sure that this function is _actually_ used by that test? We had the same problem with EVM, but found that the function should not have been called in the first place. The error was actually earlier in execution and the backend should not have gotten to the point of calling this function.

**Comment by gtrepta** [comment]
I'm not sure, it's being called as a check for builtin contracts like `ecadd` and `ecmul`. If that's a similar situation to what was happening in EVM then I guess we can get rid of it, but I need @ehildenb to weigh in.

**Comment by ehildenb** [comment]
I'm not 100%, but I believe this test is actually invoking said hook. As @ttuegel pointed out though, impementing the hook is not needed for symbolic execution, so we can leave this issue open for now. I've linked to it on the IOG project board, but we do not need to take action at this time (will be leaving that test in the failing list of KIELE repo).

The reason these are not exercised in KEVM is because there we only are executing VMTests, where any external calls (such as to the precompiled addresses) are stubbed out. On KIELE, we are actually executing the full node tests instead, so we don't get that stubbed-out behaviour.

**Comment by goodlyrottenapple** [comment]
We have a workaround for dealing with these symbolic hooks at the semantic level.
